# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/runner/work/packaged-dsdl-py/packaged-dsdl-py/submodules/zubax_dsdl/zubax/telega/setpoint/Raw9x56.0.1.dsdl
#
# Generated at:  2025-10-27 13:51:02.750013 UTC
# Is deprecated: yes
# Fixed port ID: None
# Full name:     zubax.telega.setpoint.Raw9x56
# Version:       0.1
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import warnings as _warnings_

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class Raw9x56_0_1:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 raw: None | _NDArray_[_np_.uint16] | list[int] = None) -> None:
        """
        zubax.telega.setpoint.Raw9x56.0.1
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param raw: saturated uint9[56] raw
        """
        _warnings_.warn('Data type zubax.telega.setpoint.Raw9x56.0.1 is deprecated', DeprecationWarning)

        self._raw: _NDArray_[_np_.uint16]

        if raw is None:
            self.raw = _np_.zeros(56, _np_.uint16)
        else:
            if isinstance(raw, _np_.ndarray) and raw.dtype == _np_.uint16 and raw.ndim == 1 and raw.size == 56:  # type: ignore
                # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                self._raw = raw
            else:
                # Last resort, slow construction of a new array. New memory may be allocated.
                raw = _np_.array(raw, _np_.uint16).flatten()
                if not raw.size == 56:  # Length cannot be checked before casting and flattening
                    raise ValueError(f'raw: invalid array length: not {raw.size} == 56')
                self._raw = raw
            assert isinstance(self._raw, _np_.ndarray)
            assert self._raw.dtype == _np_.uint16  # type: ignore
            assert self._raw.ndim == 1
            assert len(self._raw) == 56

    @property
    def raw(self) -> _NDArray_[_np_.uint16]:
        """
        saturated uint9[56] raw
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._raw

    @raw.setter
    def raw(self, x: _NDArray_[_np_.uint16] | list[int]) -> None:
        if isinstance(x, _np_.ndarray) and x.dtype == _np_.uint16 and x.ndim == 1 and x.size == 56:  # type: ignore
            # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
            self._raw = x
        else:
            # Last resort, slow construction of a new array. New memory may be allocated.
            x = _np_.array(x, _np_.uint16).flatten()
            if not x.size == 56:  # Length cannot be checked before casting and flattening
                raise ValueError(f'raw: invalid array length: not {x.size} == 56')
            self._raw = x
        assert isinstance(self._raw, _np_.ndarray)
        assert self._raw.dtype == _np_.uint16  # type: ignore
        assert self._raw.ndim == 1
        assert len(self._raw) == 56

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        assert len(self.raw) == 56, 'self.raw: saturated uint9[56]'
        # Element offset: concat(pad(1,pad(8,{0})),repeat(<=55,{9}))
        for _elem0_ in self.raw:
            _ser_.add_unaligned_unsigned(max(min(_elem0_, 511), 0), 9)
        _ser_.pad_to_alignment(8)
        assert 504 <= (_ser_.current_bit_length - _base_offset_) <= 504, \
            'Bad serialization of zubax.telega.setpoint.Raw9x56.0.1'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> Raw9x56_0_1:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "raw"
        _f0_ = _np_.empty(56, _np_.uint16)  # type: ignore
        for _i0_ in range(56):
            _e0_ = _des_.fetch_unaligned_unsigned(9)
            _f0_[_i0_] = _e0_
        assert len(_f0_) == 56, 'saturated uint9[56]'
        self = Raw9x56_0_1(
            raw=_f0_)
        _des_.pad_to_alignment(8)
        assert 504 <= (_des_.consumed_bit_length - _base_offset_) <= 504, \
            'Bad deserialization of zubax.telega.setpoint.Raw9x56.0.1'
        assert isinstance(self, Raw9x56_0_1)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'raw=%s' % _np_.array2string(self.raw, separator=',', edgeitems=10, threshold=100, max_line_width=1000000),
        ])
        return f'zubax.telega.setpoint.Raw9x56.0.1({_o_0_})'

    _EXTENT_BYTES_ = 63

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.StructureType = _restore_constant_(
        'ABzY8#(4i|0{?wgZEqDt6mIGJD}93^1zQo}f^=y`u=oaOLSn|&rl{Y{WcKcOXVSg9o7vg+UJ??C0VSD)(GL2<{4;#?oV}+O(Ap1u'
        '_RKlwIp@sFbAK9q@z-!){pXg8Zc-*`#7k+kNcBSzr!wNryj|p_wlcV>2i8<gTN(Lnw~*l=TzMQGg@zmAnP`Lm{KG01oyf{mwnS7)'
        'TjV;k(T>=^-MM)yxKX|*O{w!Ns6IFHJ$)Yp*2nsvhR4B8aAB>{ab;y0ehA04^iNQ5L-(~zlcQF~c_OUf7W;Ec$D|u0y1^~n*BzOB'
        'Ewh$Y_i*X;p{6*D(UzGdvSWHFjBabI_aI{ayR6i$OeSAtR<@*hoo|B2+VZq67uXnd+7zYb?L3h|opq<T4~Z}>`VxGb=)&E35_X_n'
        'URseQ!X&Q}J*#3j226!$YTFHL!wvE{ErYvs*zQp<bZ+0YgPZ(9+ukNT0F&Bv13WK+TRD!T?6%`P)lC?BQ?_&13=2p3O(Bi2xj7no'
        'm^YP%^HGtT+mVH|`oH5&@LlL#-GI20TUDA0(|t1txb{R^$?!Zh*qAS4n0%18brv>X_T!i6)L$dGrBy1Bm-S<CpJyis2M7lVhY$xn'
        '8zy^%aFlS2aGc^Mdd1l!txqA2dp1q>N%GGij(RqWIN{kG`R6Hqf%s0*`f0=k&lV9+d3J`@-=es)l(&R9=h->(pC|se5zlzGOm$bt'
        'euw(GfOyWccM+#OyGZ%(Auf7$iTE!gUi7R%`BxApJ-bTr?;|dIc8&U7CH@HUnrGJ$FL<^_`Ri2g1DfLo;;LsKQk|QKOP<}LxjrJk'
        '4XSq=am}-j5gVR;g1F+@r^Npm;*4jX)7*C`?=Iqoui%x*P9d^dXkZO4h_7P2J8H-c7_lGV<|H}X<Guje<>p@zARc#ny7nljCu+8Y'
        '7o5n#$fmF|3BS5&{v!$qFLGnKPQsR(<z-%(rUXYSc_H9^x)Fp_$H9$lgN$~zarFSMeE)T*t#Z`OVN+$9G+^)NW;eJQc+I<_C6iTr'
        'eXB(`0MU3^#r4ewX>{YY(sFcz2G$19^n@35_E36(io`csi`Jt$+@hGwb0tdX(4fA7pzZ0V4A0b4^^2RShwjOK25uDM#{bqBITU#5'
        '7VD|G&AG{QTQij~3@F_5hVtq+^}9MyFpYYl{!o8nE9$bkTEB0#s@8gH(362}kt8~6{YxvryAHo3Mb91BD4gXTI9GKS|J?(kpSOBP'
        '9Q_T|OT63O1^@s'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
