# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/runner/work/packaged-dsdl-py/packaged-dsdl-py/submodules/public_regulated_data_types/uavcan/node/IOStatistics.0.1.dsdl
#
# Generated at:  2025-09-12 07:48:14.457801 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     uavcan.node.IOStatistics
# Version:       0.1
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class IOStatistics_0_1:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 num_emitted:  None | int | _np_.uint64 = None,
                 num_received: None | int | _np_.uint64 = None,
                 num_errored:  None | int | _np_.uint64 = None) -> None:
        """
        uavcan.node.IOStatistics.0.1
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param num_emitted:  truncated uint40 num_emitted
        :param num_received: truncated uint40 num_received
        :param num_errored:  truncated uint40 num_errored
        """
        self._num_emitted:  int
        self._num_received: int
        self._num_errored:  int

        self.num_emitted = num_emitted if num_emitted is not None else 0  # type: ignore

        self.num_received = num_received if num_received is not None else 0  # type: ignore

        self.num_errored = num_errored if num_errored is not None else 0  # type: ignore

    @property
    def num_emitted(self) -> int:
        """
        truncated uint40 num_emitted
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._num_emitted

    @num_emitted.setter
    def num_emitted(self, x: int | _np_.uint64) -> None:
        """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
        x = int(x)
        if 0 <= x <= 1099511627775:
            self._num_emitted = x
        else:
            raise ValueError(f'num_emitted: value {x} is not in [0, 1099511627775]')

    @property
    def num_received(self) -> int:
        """
        truncated uint40 num_received
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._num_received

    @num_received.setter
    def num_received(self, x: int | _np_.uint64) -> None:
        """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
        x = int(x)
        if 0 <= x <= 1099511627775:
            self._num_received = x
        else:
            raise ValueError(f'num_received: value {x} is not in [0, 1099511627775]')

    @property
    def num_errored(self) -> int:
        """
        truncated uint40 num_errored
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._num_errored

    @num_errored.setter
    def num_errored(self, x: int | _np_.uint64) -> None:
        """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
        x = int(x)
        if 0 <= x <= 1099511627775:
            self._num_errored = x
        else:
            raise ValueError(f'num_errored: value {x} is not in [0, 1099511627775]')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.add_aligned_unsigned(self.num_emitted, 40)
        _ser_.add_aligned_unsigned(self.num_received, 40)
        _ser_.add_aligned_unsigned(self.num_errored, 40)
        _ser_.pad_to_alignment(8)
        assert 120 <= (_ser_.current_bit_length - _base_offset_) <= 120, \
            'Bad serialization of uavcan.node.IOStatistics.0.1'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> IOStatistics_0_1:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "num_emitted"
        _f0_ = _des_.fetch_aligned_unsigned(40)
        # Temporary _f1_ holds the value of "num_received"
        _f1_ = _des_.fetch_aligned_unsigned(40)
        # Temporary _f2_ holds the value of "num_errored"
        _f2_ = _des_.fetch_aligned_unsigned(40)
        self = IOStatistics_0_1(
            num_emitted=_f0_,
            num_received=_f1_,
            num_errored=_f2_)
        _des_.pad_to_alignment(8)
        assert 120 <= (_des_.consumed_bit_length - _base_offset_) <= 120, \
            'Bad deserialization of uavcan.node.IOStatistics.0.1'
        assert isinstance(self, IOStatistics_0_1)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'num_emitted=%s' % self.num_emitted,
            'num_received=%s' % self.num_received,
            'num_errored=%s' % self.num_errored,
        ])
        return f'uavcan.node.IOStatistics.0.1({_o_0_})'

    _EXTENT_BYTES_ = 15

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.StructureType = _restore_constant_(
        'ABzY8KG4Hx0{`vS+iu*(9R~1SX|-Cd*3#-|S$1q%c5Jzo)=qQsAxRGb0voIoB6b1?ML`V7k%kDDT#!SF>mJZtw1@!$C14f^`UH7|'
        'JVG8J=o91-a+&{--&o2fYMXmmFuvh(I0w%BX7_Kcf2He<>R*0oH1-lN7}yDqeHQpnnG^7V?MA~<l=zaD`I$#DPF<PC{PB3i%je~d'
        '&&t1)+xd(gvLW5yNZEnQ!a*2$eDL6dN0LcDk-nRhdB;BBapFf|DH{3g$0$E9&4$_hNBLQq&)ZDO*mqLNlk$($=n2DlQLD^n-t&3j'
        '9Sx&vdrUH0s<EB)_$c;=zVr{M#>z)w;_rvtdk{*#&*LA?Y2J2xX$L&qm!dRP<1S02J*26XVl`j4bVKT~!Mk+tp}IvgYW}_au*_HO'
        'M6%Fhv3I<oXQ?A*^7$|w+MFJj+$-~z?L}^x?>rXVpc@X4jcCtEQrG24vX=(I*g#!_hm!i_$)Kcm`t?Y~idaYKoVhJF#YJ(c?xv@@'
        'iMh*ZlwK(==ez%<3tjJL_EAqIj-$Bl;@|h9Lu1H78ngN^F$6o{M&!C_Of?2wH3FV7R~jDQ^F!(>3e{M)s_I(?y)r{k6H@T8!D4Q>'
        'Q5veLtFk{F1$;;YWa_cqss--tbki`Pc^JuvyZ)Z<GBqFEG$Lv#KJ*i==EL)qW82Jj#`VTk^D@MexGt`UU2!9&#rOD#-Uw3*^ekVn'
        '_xy}|_9%*_?R(|>`I4PPY3y>k5pa9NXle6V6@l-R`J6>yGE05>oVHT)CM~jvl#q6uh9QsX`Y?(=E%W|}xu3Fq?(M40x;q+|;$GfO'
        'Qit|gN|P${^P|)We3#a7KMmA)jy5^nZP((cJ!P)U*N&?j+#0+xQ0<md?Z_2du!P1M(+gB84t$rF&&1^?+s#Jfw}#%XM#809k$p}B'
        '^<BdcN2$CSrIJEbsvBnkR)&^X3MT97)tgU5lm?y=M$`<U-wUF{LHEI)!Hm~#?UDukpy4OfxEoh1sx}@~9veeH2xzt3DD-v=s(eV-'
        'FWRB{#$R83-57HgCv~IY(ama?B|B>G7zZp!dHwKV%tlouLq^6^9!G<2wGFE($?@SjoEWI-9|~I5svY%O)j-v{`QiS6maN({^|2Vz'
        '$m`Q;av^#@IR1Ekw%R1NjO;jyWYt7MYfop%8{6Vdaa-IGcf~#WdrQ16-l^8BWjg^a@il#r9UUXIdUEoby8N9le_vfcqDvfP`LrF4'
        '%G@}qkz_n{BHCZHJs$F5M8~9}^}&eNQbzI7aoDz9dM8BualU9V&!czoqe|iv@$rk&<9zMiC{%*NpKLOpt6QYqs9xZ)C;#vht+A>k'
        'ypw9usNSbzjK$+0_0zVig)aYDZkyXh;?P&osGa~F)u}_TdFY4ggr@?_RAJVx^fA@8*-_6m3bTovLQbn}7G?|AGsw2eR$<PnoGHvX'
        'Tz7GQUgd0I_VD=`w6mbHSD1?`yM@_T*(uB=mF>b@M*S6)Q-!&T_SRIc6z00h<-$Cxa;Y#kRQ3z=oXW+*+*G+xnCDfVDa;G#?<JM<'
        'g?SPEUQ#(%m<Ia4jPY(^99J-}s~FGADyIwc8pd@U^V!DuZq)DH`~~ut$Q|S^a)7*vyoG!P`77kB$k&jsBi}&2iM)-xgS?BphkOh9'
        'Hu4?huaUn&-bX$`3S@@-9Qg(EOXOF`uaVy%zeRpm=fh4Dg$-TU)`i=;a9<am=z`FNOcy@ag)emBOI`R%7rxeoZ*<{XUHA@#lz!;&'
        'Y{bIq_ZdEOgslA?YD7G7#8cA}f1>|?{+~>yPGB+xCevWjnP4&vCLJ)D0+TM7%z#M)OnP9_0h87QlO-@&0F!wz>43=$m`s7mCYWr1'
        '$vT*<g2^(N^uc5SOnP9_1(Ob#w85kWCQ}nku7k-nFnJkFu7b%GFxdi=%V1)F$t5tk2qrIq$ptVu4<?&nat=&3z~n5Ltb@rKn5=@y'
        '3YaW|$r70K!K4Ew7MNIIVu6VTCKi}jU}AxZ1tu1lSYTplCYEMmX(pCtVreFpW@2e3mS$pUCYEMmX(pCtVreFpW@2e3mS$oVsrU~H'
        'ju@-2ky8z)8csEw_)U?KjqLxh(Kx|I12&qlF+E|U3mXmCn1+oGY&0f*P&Hwr2OI4P8;h{fg^d~5Xu!rQZ1iEH2OAyOXu(DUHqOJw'
        '25hXs#xiUy!bT4^=3t`@8`BduuEEAt*w}&%12!(g#s%2egpCc@Sci>O*jR>*K5Q(&Mh`Z+u+f2yHf*$DV+uAJuyGGI?!v|$*tiWF'
        'w_wA7jXrENU?YQ#3^p>@$Y3LbjSMz2*vPbvOxwt`jZE9fw2e&L$h3`2+sL$yOxwt`jZE9fw2e&L$h3`2+sL$ytp29xq^BBAHJoZ7'
        '4T+OFgYN;{nZ<#C761S'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
