# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2025-11-24 13:46:53.829443 UTC
# Namespace:     uavcan.metatransport

# There are no data types in this namespace. There may be data types in nested namespaces.
