# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2025-09-11 16:13:19.406531 UTC
# Namespace:     uavcan.si.sample

# There are no data types in this namespace. There may be data types in nested namespaces.
