# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2025-10-27 13:51:00.986083 UTC
# Namespace:     reg.udral.service.sensor

from reg.udral.service.sensor.Status_0_1 import Status_0_1 as Status_0_1

# Convenience aliases of the newest minor versions known at the time of code generation.
Status_0 = Status_0_1
