# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/runner/work/packaged-dsdl-py/packaged-dsdl-py/submodules/starcopter-dsdl/starcopter/aeric/motherboard/SystemState.0.1.dsdl
#
# Generated at:  2025-10-27 13:51:01.674533 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     starcopter.aeric.motherboard.SystemState
# Version:       0.1
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import uavcan.time

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class SystemState_0_1:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 timestamp: None | uavcan.time.SynchronizedTimestamp_1_0 = None,
                 pssky1_on: None | bool = None,
                 pssky1_pg: None | bool = None,
                 pssky2_on: None | bool = None,
                 pssky2_pg: None | bool = None,
                 psmmb_on:  None | bool = None,
                 psmmb_pg:  None | bool = None,
                 psppb_on:  None | bool = None,
                 psppb_pg:  None | bool = None) -> None:
        """
        starcopter.aeric.motherboard.SystemState.0.1
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param timestamp: uavcan.time.SynchronizedTimestamp.1.0 timestamp
        :param pssky1_on: saturated bool pssky1_on
        :param pssky1_pg: saturated bool pssky1_pg
        :param pssky2_on: saturated bool pssky2_on
        :param pssky2_pg: saturated bool pssky2_pg
        :param psmmb_on:  saturated bool psmmb_on
        :param psmmb_pg:  saturated bool psmmb_pg
        :param psppb_on:  saturated bool psppb_on
        :param psppb_pg:  saturated bool psppb_pg
        """
        self._timestamp: uavcan.time.SynchronizedTimestamp_1_0
        self._pssky1_on: bool
        self._pssky1_pg: bool
        self._pssky2_on: bool
        self._pssky2_pg: bool
        self._psmmb_on:  bool
        self._psmmb_pg:  bool
        self._psppb_on:  bool
        self._psppb_pg:  bool

        if timestamp is None:
            self.timestamp = uavcan.time.SynchronizedTimestamp_1_0()
        elif isinstance(timestamp, uavcan.time.SynchronizedTimestamp_1_0):
            self.timestamp = timestamp
        else:
            raise ValueError(f'timestamp: expected uavcan.time.SynchronizedTimestamp_1_0 '
                             f'got {type(timestamp).__name__}')

        self.pssky1_on = pssky1_on if pssky1_on is not None else False

        self.pssky1_pg = pssky1_pg if pssky1_pg is not None else False

        self.pssky2_on = pssky2_on if pssky2_on is not None else False

        self.pssky2_pg = pssky2_pg if pssky2_pg is not None else False

        self.psmmb_on = psmmb_on if psmmb_on is not None else False

        self.psmmb_pg = psmmb_pg if psmmb_pg is not None else False

        self.psppb_on = psppb_on if psppb_on is not None else False

        self.psppb_pg = psppb_pg if psppb_pg is not None else False

    @property
    def timestamp(self) -> uavcan.time.SynchronizedTimestamp_1_0:
        """
        uavcan.time.SynchronizedTimestamp.1.0 timestamp
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, x: uavcan.time.SynchronizedTimestamp_1_0) -> None:
        if isinstance(x, uavcan.time.SynchronizedTimestamp_1_0):
            self._timestamp = x
        else:
            raise ValueError(f'timestamp: expected uavcan.time.SynchronizedTimestamp_1_0 got {type(x).__name__}')

    @property
    def pssky1_on(self) -> bool:
        """
        saturated bool pssky1_on
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._pssky1_on

    @pssky1_on.setter
    def pssky1_on(self, x: bool) -> None:
        self._pssky1_on = bool(x)  # Cast to bool implements saturation

    @property
    def pssky1_pg(self) -> bool:
        """
        saturated bool pssky1_pg
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._pssky1_pg

    @pssky1_pg.setter
    def pssky1_pg(self, x: bool) -> None:
        self._pssky1_pg = bool(x)  # Cast to bool implements saturation

    @property
    def pssky2_on(self) -> bool:
        """
        saturated bool pssky2_on
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._pssky2_on

    @pssky2_on.setter
    def pssky2_on(self, x: bool) -> None:
        self._pssky2_on = bool(x)  # Cast to bool implements saturation

    @property
    def pssky2_pg(self) -> bool:
        """
        saturated bool pssky2_pg
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._pssky2_pg

    @pssky2_pg.setter
    def pssky2_pg(self, x: bool) -> None:
        self._pssky2_pg = bool(x)  # Cast to bool implements saturation

    @property
    def psmmb_on(self) -> bool:
        """
        saturated bool psmmb_on
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._psmmb_on

    @psmmb_on.setter
    def psmmb_on(self, x: bool) -> None:
        self._psmmb_on = bool(x)  # Cast to bool implements saturation

    @property
    def psmmb_pg(self) -> bool:
        """
        saturated bool psmmb_pg
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._psmmb_pg

    @psmmb_pg.setter
    def psmmb_pg(self, x: bool) -> None:
        self._psmmb_pg = bool(x)  # Cast to bool implements saturation

    @property
    def psppb_on(self) -> bool:
        """
        saturated bool psppb_on
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._psppb_on

    @psppb_on.setter
    def psppb_on(self, x: bool) -> None:
        self._psppb_on = bool(x)  # Cast to bool implements saturation

    @property
    def psppb_pg(self) -> bool:
        """
        saturated bool psppb_pg
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._psppb_pg

    @psppb_pg.setter
    def psppb_pg(self, x: bool) -> None:
        self._psppb_pg = bool(x)  # Cast to bool implements saturation

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.timestamp._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.skip_bits(8)
        _ser_.add_unaligned_bit(self.pssky1_on)
        _ser_.add_unaligned_bit(self.pssky1_pg)
        _ser_.add_unaligned_bit(self.pssky2_on)
        _ser_.add_unaligned_bit(self.pssky2_pg)
        _ser_.add_unaligned_bit(self.psmmb_on)
        _ser_.add_unaligned_bit(self.psmmb_pg)
        _ser_.add_unaligned_bit(self.psppb_on)
        _ser_.add_unaligned_bit(self.psppb_pg)
        _ser_.pad_to_alignment(8)
        assert 72 <= (_ser_.current_bit_length - _base_offset_) <= 72, \
            'Bad serialization of starcopter.aeric.motherboard.SystemState.0.1'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> SystemState_0_1:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "timestamp"
        _des_.pad_to_alignment(8)
        _f0_ = uavcan.time.SynchronizedTimestamp_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f1_ holds the value of ""
        _des_.skip_bits(8)
        # Temporary _f2_ holds the value of "pssky1_on"
        _f2_ = _des_.fetch_unaligned_bit()
        # Temporary _f3_ holds the value of "pssky1_pg"
        _f3_ = _des_.fetch_unaligned_bit()
        # Temporary _f4_ holds the value of "pssky2_on"
        _f4_ = _des_.fetch_unaligned_bit()
        # Temporary _f5_ holds the value of "pssky2_pg"
        _f5_ = _des_.fetch_unaligned_bit()
        # Temporary _f6_ holds the value of "psmmb_on"
        _f6_ = _des_.fetch_unaligned_bit()
        # Temporary _f7_ holds the value of "psmmb_pg"
        _f7_ = _des_.fetch_unaligned_bit()
        # Temporary _f8_ holds the value of "psppb_on"
        _f8_ = _des_.fetch_unaligned_bit()
        # Temporary _f9_ holds the value of "psppb_pg"
        _f9_ = _des_.fetch_unaligned_bit()
        self = SystemState_0_1(
            timestamp=_f0_,
            pssky1_on=_f2_,
            pssky1_pg=_f3_,
            pssky2_on=_f4_,
            pssky2_pg=_f5_,
            psmmb_on=_f6_,
            psmmb_pg=_f7_,
            psppb_on=_f8_,
            psppb_pg=_f9_)
        _des_.pad_to_alignment(8)
        assert 72 <= (_des_.consumed_bit_length - _base_offset_) <= 72, \
            'Bad deserialization of starcopter.aeric.motherboard.SystemState.0.1'
        assert isinstance(self, SystemState_0_1)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'timestamp=%s' % self.timestamp,
            'pssky1_on=%s' % self.pssky1_on,
            'pssky1_pg=%s' % self.pssky1_pg,
            'pssky2_on=%s' % self.pssky2_on,
            'pssky2_pg=%s' % self.pssky2_pg,
            'psmmb_on=%s' % self.psmmb_on,
            'psmmb_pg=%s' % self.psmmb_pg,
            'psppb_on=%s' % self.psppb_on,
            'psppb_pg=%s' % self.psppb_pg,
        ])
        return f'starcopter.aeric.motherboard.SystemState.0.1({_o_0_})'

    _EXTENT_BYTES_ = 63

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.DelimitedType = _restore_constant_(
        'ABzY8#d!Z{0{`t;TW{RP6<*o0wYvBg*|K6M_PB0rIguD!jcnDu#Fl&u7|V*}xNeJ<<&vWvN?Z=Zi==g0pm}Iv0|ZLIERdg&pAhsH'
        '1n3_KiU#Ogg8)SyiUKL}(0+#;?yh!MLERvIss+zCoH@6dGjq<F{q^AQ|1eR>|0SpWrXAX@W`sO&OxJm2)?BU`mTdSkbRwQ52X1iJ'
        'X`pN0Z~8oYnq7D=`&BlT>^B_G<3T1W$$`}<h^;6N_)e02hG#Y)Vk(Txz><E%1I>gUOKZqT@SrBmz}8lqVZ<A&kxAOB#wHI!M|vc8'
        '=z;1#&Gd>s@Z0RYEEzS-C<>ff9Pu#w8I<g@f)-Vl?7QV~*KV6NV%TP68WGtlhKfNklAMXnP0RGO$Z2pG<yj(-p7RLn#sF5(@G~(c'
        '4(bDXg)9+Apj{kO?326M;Rm#N&L->_f7=V4y2tG|yolF%uyeCUjhYh~F8At@$n<$wX_;YUG^7nH&m<Ger66L{7BP31rm!^wzsXjz'
        '<fs7~JsUgPDd<UD!_r0@jups|Thg<$WYDmsl|B4yPo;8SaOTC08V{IUV;xi>i-Z|5VQzBfn_<Xp7CN5AStuKvnE_M;X3%5}e0mXc'
        'JkaNqkv2j?)i{L8z^P+;%F(zsom0^Uvzi(53(N_b&DR|43G;a{WBR`9SY`yDYmCHLaS)K477J;LLp}mWu^MLqe<y}-z`hp9Mq7H='
        'a$hctHDDMIrdh~&PGm{Q4Sg)s@#+{2HXW=jH^s@dk6;xrZqsyQPF6;ed3=+$3C)@-w+j1O^K+MHuqABEv0*2-OxSpJWQ4I9Hv99r'
        '%R6@#<YrCA5u2TzpJPpK2H`Z@5{@Nk%7^EorpB(b%dh1!J9uGtjI$H4Eg8Eu6hQ-HG47$o!_W*Iw^^8ggTS09Y*~wK0~@R*kIX@9'
        'BxD>CRjwY>b_@~Bgf<A~+Ya{2i*Sya6*!?2YQ<s}U7Q8SnpwQQ#HKtMv0FDTFq{Mrdl^8VWd=ADu}}MTh1Ht4q@>X|o31o-AHz|I'
        '30iLW{nAyeLFU&%917EQ$-{Kq>Mozj$qN;0yuDEkj)CHgMlC<!P@IqGSkN8>H0!}J44W8g87{(jQeBiDU6ZJF@5H1yt9s}3d2wD`'
        '&?|JG#B_0WhTdM%m+t*&DHB?9?k7Bu-Kz8R2EWm6Y<P0Z(=x=y+@LIZu?z})+sA>UV74P9R9EuzX}YC7;%YLCC0jHaV*Zxuw?g1b'
        '7S`e#PsTgqpiyfUk(O35BTkEXF&iVG*c?i6ow%JnNe&uo&NjCVa+KlN*-~=E2xS~t91|`#d=ud!86t3<T9yniBLQqL)96!#r-4@y'
        'IE18dzCVcb$e#>u$zUT(4*RCH0q@x}wALBFnTfZOkua_ycEv8jbaK*<Yq;1(!0WL~_Ov4~X7?9?7xHK?v*c9Y;HzEIE^4G8izwWU'
        '8^R1>G=&F4UEu5qob<<~A|Q|kMjGfeAwI|e(Sn>n=NgyZ#D$J%0W<lH2|IM=KFyWlBt>G!4TJ#c#zl<CLquB-K7>;jxP#br*+2la'
        'm0~*2HKaU>US*Wd@8~9IWH1x@+;Y~Oj(dOvvcYkZ4(E<7^05cYi=5ZJW5@cZE1n$B-D*VA2&9a1Ss}cIjPmA`xGR>#J+Um_!rzKm'
        '75DRv9W-h#oN}%_x$R_vZH~IXvt(?+iQde=S9$ANC3_9&X9?R)NZ4%DBu)hUc$YV%3e)!xAIwMwokfNv5Rfvlo*Y^>ZHm@CL_*T+'
        'QtY}&NZqsI>hH2CeLf9qC@uU#LZ(;a8rIoxJW90anA_ADGV%j!l2Cns_$sNsN8w(=J*hsZzV{Ihr22j}KBUI03WwGB2;u%zA64{Y'
        'gw<3(KscD{2NnGx!qHSetmcmp?o0LOl$>$G=TiMB;o($2MtCsQCkV$<{W#%Bs!uBZ=at?QO3z6p=LMzjMZ%M*ev0r!s-Gr&KGhlF'
        'WU8MbJf7;`BAiI|vxLV|{o8~`Q~f2v@l-#j>^e_)B-N*seHRE1rTWXt&Q}Nzr24e7cSfyOQ+B^fIGpMimHn3phf;l3t>ZgtKVDPo'
        'nIqhr>X+5JuBiQ;SL^$3;dfp6U;m!M?<@R)!XGMpUEwu_cN9KUC=_lhe5~+&g&!#VP~k@kKUVmu!Y>NETOClH$+9z5cIL~@owD<='
        '?1-|nU3MOqo%hSm2W98Ovhz{d`MB(ST6Vrrof!2dauhNfB^xzXqf~<&I2^SrU@fT>sdP-;$DPGB3gHv|3*k+Pq?1%106Gg_WZh~A'
        'CE^pIiBBN8RZ*kp9bJ&pMY`QlDT8AGdHPD3p@;o2+-P1h=*^%dFU>t*s~b%ZwK1cT88P81+mvpEu!?+*@GT_l-J$5SuNLgrN${zD'
        'f_=G#LZdF_vq+p(rk?MRxSD5|uWjtCGM4oh{fy>T{jkxfDQl-@A@i<8Y(<MIlr7Nf?Y}iwi7u=?vy13wH`n(|b6+Nz%g(kiw>H?a'
        'sy`Rv@M{=M!V81X?kaqT$z0qdNq-g-;&0-w;_u>f@lWv&@h|b^`o4imWqp8}QEG;$IYP|=YK~JgjwTkjpNKn4;*Fksog8XEs`I)l'
        'L&?<|!J{{SXyd)y@zlm6vE#9ga_UmMpb|f(;^}P8#WpW$v*eJHkriyLc%+M;QVsGSXdCT(+H>)Xo<*#mpoN}9lbc|PwIU`s!foaD'
        'cUnESBi|oGAy1X9*SBy;hKsrZ#Ua&8UoCBY7W(s#^*QwZPyfH6Z-}NofUETguda9T|CjLlpO!EXcNA__6mC2uqH7?!)+Q=>yM{Y?'
        '2U@(>L3F*Bw`;gR?*fPxdU?Bs`|~b>Xt9^KYq&q}4G`Vv<?R~o&wCR@H+y-zhWqp00@1Br-mc;PythGgyO+0XxIgb55Z&qIt;W5>'
        'MLi-$#h5r;{Qfo}{({K*Iil*9MK~R51yPEh-(&=C2e0)PsCki^Q)MipaJqg5U*A-;#B+sj(~mS6inwF~kNx6j+Q1Opv;oEMo9!Pr'
        '7}D7*V)`+*uwS6<b8S04#o(zO5%~Cu>DBoP_j%;(_ITSUo>s4eq5D?n-mQptVLZ9Fd^d%;pNk{GFgv-Ycb1s7e*<8V{{h7o000'
    )
    assert isinstance(_MODEL_, _pydsdl_.DelimitedType)
