# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/runner/work/packaged-dsdl-py/packaged-dsdl-py/submodules/starcopter-dsdl/starcopter/highdra/bms/State.0.1.dsdl
#
# Generated at:  2025-11-24 13:46:55.548680 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     starcopter.highdra.bms.State
# Version:       0.1
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import starcopter.highdra.bms
import uavcan.time

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class State_0_1:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 timestamp:      None | uavcan.time.SynchronizedTimestamp_1_0 = None,
                 boot_pin_state: None | bool = None,
                 chg_pin_state:  None | bool = None,
                 dsg_pin_state:  None | bool = None,
                 hs_en:          None | bool = None,
                 hs_ok:          None | bool = None,
                 scp_active:     None | bool = None,
                 can_state:      None | starcopter.highdra.bms.CanState_0_1 = None,
                 button_state:   None | starcopter.highdra.bms.ButtonState_0_1 = None,
                 location:       None | starcopter.highdra.bms.Location_0_1 = None) -> None:
        """
        starcopter.highdra.bms.State.0.1
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param timestamp:      uavcan.time.SynchronizedTimestamp.1.0 timestamp
        :param boot_pin_state: saturated bool boot_pin_state
        :param chg_pin_state:  saturated bool chg_pin_state
        :param dsg_pin_state:  saturated bool dsg_pin_state
        :param hs_en:          saturated bool hs_en
        :param hs_ok:          saturated bool hs_ok
        :param scp_active:     saturated bool scp_active
        :param can_state:      starcopter.highdra.bms.CanState.0.1 can_state
        :param button_state:   starcopter.highdra.bms.ButtonState.0.1 button_state
        :param location:       starcopter.highdra.bms.Location.0.1 location
        """
        self._timestamp:      uavcan.time.SynchronizedTimestamp_1_0
        self._boot_pin_state: bool
        self._chg_pin_state:  bool
        self._dsg_pin_state:  bool
        self._hs_en:          bool
        self._hs_ok:          bool
        self._scp_active:     bool
        self._can_state:      starcopter.highdra.bms.CanState_0_1
        self._button_state:   starcopter.highdra.bms.ButtonState_0_1
        self._location:       starcopter.highdra.bms.Location_0_1

        if timestamp is None:
            self.timestamp = uavcan.time.SynchronizedTimestamp_1_0()
        elif isinstance(timestamp, uavcan.time.SynchronizedTimestamp_1_0):
            self.timestamp = timestamp
        else:
            raise ValueError(f'timestamp: expected uavcan.time.SynchronizedTimestamp_1_0 '
                             f'got {type(timestamp).__name__}')

        self.boot_pin_state = boot_pin_state if boot_pin_state is not None else False

        self.chg_pin_state = chg_pin_state if chg_pin_state is not None else False

        self.dsg_pin_state = dsg_pin_state if dsg_pin_state is not None else False

        self.hs_en = hs_en if hs_en is not None else False

        self.hs_ok = hs_ok if hs_ok is not None else False

        self.scp_active = scp_active if scp_active is not None else False

        if can_state is None:
            self.can_state = starcopter.highdra.bms.CanState_0_1()
        elif isinstance(can_state, starcopter.highdra.bms.CanState_0_1):
            self.can_state = can_state
        else:
            raise ValueError(f'can_state: expected starcopter.highdra.bms.CanState_0_1 '
                             f'got {type(can_state).__name__}')

        if button_state is None:
            self.button_state = starcopter.highdra.bms.ButtonState_0_1()
        elif isinstance(button_state, starcopter.highdra.bms.ButtonState_0_1):
            self.button_state = button_state
        else:
            raise ValueError(f'button_state: expected starcopter.highdra.bms.ButtonState_0_1 '
                             f'got {type(button_state).__name__}')

        if location is None:
            self.location = starcopter.highdra.bms.Location_0_1()
        elif isinstance(location, starcopter.highdra.bms.Location_0_1):
            self.location = location
        else:
            raise ValueError(f'location: expected starcopter.highdra.bms.Location_0_1 '
                             f'got {type(location).__name__}')

    @property
    def timestamp(self) -> uavcan.time.SynchronizedTimestamp_1_0:
        """
        uavcan.time.SynchronizedTimestamp.1.0 timestamp
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, x: uavcan.time.SynchronizedTimestamp_1_0) -> None:
        if isinstance(x, uavcan.time.SynchronizedTimestamp_1_0):
            self._timestamp = x
        else:
            raise ValueError(f'timestamp: expected uavcan.time.SynchronizedTimestamp_1_0 got {type(x).__name__}')

    @property
    def boot_pin_state(self) -> bool:
        """
        saturated bool boot_pin_state
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._boot_pin_state

    @boot_pin_state.setter
    def boot_pin_state(self, x: bool) -> None:
        self._boot_pin_state = bool(x)  # Cast to bool implements saturation

    @property
    def chg_pin_state(self) -> bool:
        """
        saturated bool chg_pin_state
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._chg_pin_state

    @chg_pin_state.setter
    def chg_pin_state(self, x: bool) -> None:
        self._chg_pin_state = bool(x)  # Cast to bool implements saturation

    @property
    def dsg_pin_state(self) -> bool:
        """
        saturated bool dsg_pin_state
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._dsg_pin_state

    @dsg_pin_state.setter
    def dsg_pin_state(self, x: bool) -> None:
        self._dsg_pin_state = bool(x)  # Cast to bool implements saturation

    @property
    def hs_en(self) -> bool:
        """
        saturated bool hs_en
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._hs_en

    @hs_en.setter
    def hs_en(self, x: bool) -> None:
        self._hs_en = bool(x)  # Cast to bool implements saturation

    @property
    def hs_ok(self) -> bool:
        """
        saturated bool hs_ok
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._hs_ok

    @hs_ok.setter
    def hs_ok(self, x: bool) -> None:
        self._hs_ok = bool(x)  # Cast to bool implements saturation

    @property
    def scp_active(self) -> bool:
        """
        saturated bool scp_active
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._scp_active

    @scp_active.setter
    def scp_active(self, x: bool) -> None:
        self._scp_active = bool(x)  # Cast to bool implements saturation

    @property
    def can_state(self) -> starcopter.highdra.bms.CanState_0_1:
        """
        starcopter.highdra.bms.CanState.0.1 can_state
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._can_state

    @can_state.setter
    def can_state(self, x: starcopter.highdra.bms.CanState_0_1) -> None:
        if isinstance(x, starcopter.highdra.bms.CanState_0_1):
            self._can_state = x
        else:
            raise ValueError(f'can_state: expected starcopter.highdra.bms.CanState_0_1 got {type(x).__name__}')

    @property
    def button_state(self) -> starcopter.highdra.bms.ButtonState_0_1:
        """
        starcopter.highdra.bms.ButtonState.0.1 button_state
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._button_state

    @button_state.setter
    def button_state(self, x: starcopter.highdra.bms.ButtonState_0_1) -> None:
        if isinstance(x, starcopter.highdra.bms.ButtonState_0_1):
            self._button_state = x
        else:
            raise ValueError(f'button_state: expected starcopter.highdra.bms.ButtonState_0_1 got {type(x).__name__}')

    @property
    def location(self) -> starcopter.highdra.bms.Location_0_1:
        """
        starcopter.highdra.bms.Location.0.1 location
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._location

    @location.setter
    def location(self, x: starcopter.highdra.bms.Location_0_1) -> None:
        if isinstance(x, starcopter.highdra.bms.Location_0_1):
            self._location = x
        else:
            raise ValueError(f'location: expected starcopter.highdra.bms.Location_0_1 got {type(x).__name__}')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.timestamp._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.skip_bits(8)
        _ser_.add_unaligned_bit(self.boot_pin_state)
        _ser_.add_unaligned_bit(self.chg_pin_state)
        _ser_.add_unaligned_bit(self.dsg_pin_state)
        _ser_.add_unaligned_bit(self.hs_en)
        _ser_.add_unaligned_bit(self.hs_ok)
        _ser_.add_unaligned_bit(self.scp_active)
        _ser_.pad_to_alignment(8)
        self.can_state._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.button_state._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.location._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        assert 96 <= (_ser_.current_bit_length - _base_offset_) <= 96, \
            'Bad serialization of starcopter.highdra.bms.State.0.1'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> State_0_1:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "timestamp"
        _des_.pad_to_alignment(8)
        _f0_ = uavcan.time.SynchronizedTimestamp_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f1_ holds the value of ""
        _des_.skip_bits(8)
        # Temporary _f2_ holds the value of "boot_pin_state"
        _f2_ = _des_.fetch_unaligned_bit()
        # Temporary _f3_ holds the value of "chg_pin_state"
        _f3_ = _des_.fetch_unaligned_bit()
        # Temporary _f4_ holds the value of "dsg_pin_state"
        _f4_ = _des_.fetch_unaligned_bit()
        # Temporary _f5_ holds the value of "hs_en"
        _f5_ = _des_.fetch_unaligned_bit()
        # Temporary _f6_ holds the value of "hs_ok"
        _f6_ = _des_.fetch_unaligned_bit()
        # Temporary _f7_ holds the value of "scp_active"
        _f7_ = _des_.fetch_unaligned_bit()
        # Temporary _f8_ holds the value of "can_state"
        _des_.pad_to_alignment(8)
        _f8_ = starcopter.highdra.bms.CanState_0_1._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f9_ holds the value of "button_state"
        _des_.pad_to_alignment(8)
        _f9_ = starcopter.highdra.bms.ButtonState_0_1._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f10_ holds the value of "location"
        _des_.pad_to_alignment(8)
        _f10_ = starcopter.highdra.bms.Location_0_1._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        self = State_0_1(
            timestamp=_f0_,
            boot_pin_state=_f2_,
            chg_pin_state=_f3_,
            dsg_pin_state=_f4_,
            hs_en=_f5_,
            hs_ok=_f6_,
            scp_active=_f7_,
            can_state=_f8_,
            button_state=_f9_,
            location=_f10_)
        _des_.pad_to_alignment(8)
        assert 96 <= (_des_.consumed_bit_length - _base_offset_) <= 96, \
            'Bad deserialization of starcopter.highdra.bms.State.0.1'
        assert isinstance(self, State_0_1)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'timestamp=%s' % self.timestamp,
            'boot_pin_state=%s' % self.boot_pin_state,
            'chg_pin_state=%s' % self.chg_pin_state,
            'dsg_pin_state=%s' % self.dsg_pin_state,
            'hs_en=%s' % self.hs_en,
            'hs_ok=%s' % self.hs_ok,
            'scp_active=%s' % self.scp_active,
            'can_state=%s' % self.can_state,
            'button_state=%s' % self.button_state,
            'location=%s' % self.location,
        ])
        return f'starcopter.highdra.bms.State.0.1({_o_0_})'

    _EXTENT_BYTES_ = 63

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.DelimitedType = _restore_constant_(
        'ABzY8&tW8K0{`t9TWl29b=UZ@eqeA6#(@Brqy>}UA&>wrO&V;o25Vrw*)@*_wZrVpwePHFXNGy$UeZ>LqP8H7)RCA<>1X>D^`rgh'
        '4<G&MN2REh`W;n`l)oaR<fHv4A8plhX723UfK8hAqd__6?!D)nd+vGf`up8KDI7>e|M>^4s_Lk^AUV|5WL>*0mvkyfidnHtM{{ZD'
        'Z$D3UtpZDRv1-xqUU>Aq@VnuJ-z#Z`LG6&G{Ov{8_7vB%X){TWWXKf|@q**ZwqjZ?wFRavGu4)bQpFL9u8cQiq*ZD=nrWb{zN>tF'
        'FBDT^`iJ3rp+6|eu4`*0&!tZIEfBnc)-|fo@0ru6uGUo<kW|@~B^UK$eeot6@DF+Nsv;YLt5v8_tQrclO+&j4Z-ouex?+WFhz*Nr'
        'F@>725xAZ0=IrAe>0#MuFl`m|7`<XR+Ok2_dBdg4)NVG=pj6UaNvFoL%R+Gqv{Yorl`5tRS|0Mp@`)g16K3J;G9H0x(mx0bp}$K4'
        '9Sv2s)kZ;gy%Icau%aop=}^Tq)X?viR8tABKkQ1S78xamS1D1Om`kLA${{Y3UBcv5N-WuNs7f5oP$+TC3MH})SJ<*$B^CH+xI{C6'
        'KB9Dm0TjyjL8xhK%WyoQ2~;>1QK5lJNp|Q_qB%sROB&dOSk#`BElbxF*#(~q1jQ(xZKIqT3*O{8bO0PhN|f02mIuB8_9fe_)TKK$'
        '_eH`;1r($9G2&1f5h*6fbu4(OW-P<5y{f_6B2~2L_5pYWD7Px>9z`u(lNfXr%>-acH`ikQYUig;Pl8Fvnx=xDRFOf)vjYQ!Op=q|'
        'K6Sd;vOq4EOwT1JPfnd8RVv%gF|x)qh2fC}o^z`LnI@-Sk7PFRg5Dm)j!o7~Pgmh0xPcH4a!;X-Biou@ja7g^Ae!scv<0&P8)%Cj'
        'IR&@6%=8?jimr!a)dLYkhTA|eUDv=~h6`~_6kBsNM~ELYt3xbk%H-^Hj!YP)OXkiWB@hV)*wTjk6xoKL@GP{~8B(f3lH!e)T-8lE'
        '@-a9H>VOa_zL>a*R8ak8Aa<Cn>*!$&w`HA9M&$7oOSEpN3Wbe0M%|hpASjNw7#3&)8&3^z3;`oLLI{a4>Stz61JlH<<sBPmFY(o3'
        'af%&bN5vH86FU~CPT!TBm|M7(3z^^_euvs->(x=bf#1*?D~7pd2qDzNNTJZ*pA-eUZb86dF>5LbnL-qwvYzO}&ieiEWCeE}IG^L|'
        'S_v$KPRT1#f3%?vN~LOCUGWu@>>!(BCp{=ADuqiSov0e#^@pV;ZJnwTI!e;iFz1g*j_KJ7g#(>RmJH>>??a?(rO@xsL(yN)<L*5u'
        'PwC@OIGBkgyw~=kYVUWinf6NP@3drP1-z$D;#()JYRKO92OO^iwae3?O#AyRuLOxL*>u^{QJ;DRhST1-@Pa(FW#}L1SbT*O!m9#a'
        '5V~0IMkOXYpfr{Ti6?M)7o7BmTwD<F27)(WG(mkZZKxLL1dMA)dKnVh#Rp7A8RInE8TmB26e7uGO&JIROx=rXL{uW`_rM42Xpn<o'
        'b+ZBmP~{h6JeN$61l234(ov4C0*z@;Iu=#5C9NS3pn<GVh@_p7W8)rdfaY<}Yqi+!&h3i&dm^_=t|{53=|-{~@D_BGOB3ue%drKP'
        'XK%y50xPn`$gtf~Ne8DKP9nG7Ou)=;>*vrPn$g@#(dQzqrIo);GOf@j8wqi$m68b&0e-wpD<&_~3s4_q*R&f43xz>J3R&6Tk(X7h'
        ')@?-0#M7Lo>(G!|PubZYhZEvd;FMsruwn_JnDI*R&WdJWqlJaMj*C7i3RoG1ifQCa1!5P++YomJVmJTXgE$?Cy?noq?`Jsf=lcVQ'
        'djoNh(+?re1mbqY-GMmF>31L=48)!Md<1b%AU?<Cj3Rz65O*Qo8Hl?P4+r8H;-Ns?gLohi$2tG={NBC%o_$=-3;e$Qi1!8J0mOR)'
        '@gU;o1Cbye55z-=_XOgLh{po)CB(Y}@hgaT1>#o`j|SpluGbO7BY`-<^*f4qM<Bk;^?U{K_CP$w^_}GJ6}aBV5%&k;t6cvRi2DNZ'
        'B!9<i+#av<_nbn!Ef7!hcb(z(o#OBNTI_d``(OMz$8T`_Cdc34_$`jlaeR^E>l`zV*Ezn!@dq4#$nkxSKjQdfjvsLRD8`pFX}%aw'
        '78A*0Dp_1i7T1#nOBU<N;!d*oAX$8vEbb?ZkCMg5$>Kq>c*GYT%$v}optE7K;d>=)HP8e5-TDM9_^G&+4)J_!9<E^!-rIQ)UNxcV'
        '_?fGK8V6tKx)}#9VV^L8eFBne6EzIIgEOY7L%VI7lz}4+efmt&p@&OY+APh$0T|}}HaQPF^KDny@>bYXXDe(y%#o<EDROh=smTW%'
        '#gcGRSnZ%u{VUGF4ZeKM%0~SCEBb=NziPF7!D$$ix|=j@vcridk&nUXC>0l{7qe2fP*^BP)3b~7SF;g6JImhWRh!K;jyq2lyQfv`'
        'wdq1`K6jym-1IZa%}*DLo%QY7jNFmB+?gvyX<=@zgT!rHlvrF`$mg@?J4ozq7$I2}q?AX~sZ@Cff^h`95FA3VAHmBA4kLIC!Epp{'
        'AeaK+u?u(E#T=V&8z%f6^+1b;!Vn^~wgXcp4?dU^ApAnmod+O{cqi&Z9{c9q=m|G)=6S4uOf7;byV<5rc?MOU1rSM9*ivi}jp?-!'
        ';#O_tH4F~jFgUO(&I|0em|^e2|KEYLKjrGR5$3RsN<lsGUfdw@W<1w5x1M{wrHKEjlP^=qUdm1vJBG%l(ycFF$QC=x*;INBU0TRp'
        'kTw>!shsMY&t09qG~Y?ij<&d8#*k1D=m;1B55X-2-$QU4!H*EU|JZ1+hgbPLf-C@kSA%P}8r6f1;qhe$_D~#KPmb-4n#v_J{v~HC'
        'ft}H7%ugBG{R{bQPP#T<c;;5pJG+oy%od(CwEJc+P8Tk8l=Gj9>R)0!`~tzR5&R0lZxGx^@H+&*Mes)izu$aRk0egra-pt8#g`q='
        'tsxa#jQyF7vCr6F*k9S_?C<Pv>>un=ISmT1f0lbunJxtHAm~HzGXysfJV5aC&6{v|qmtl{%v>&#V%2eJg&>jVgim47o-e9A=nY?|'
        'ch8yz{%~Y;{9f+&$6w2B7-%t_A1kf=FStMYP)>KHQvav_-=wcV_N1finS$(@s%1}8mSrHzsDni3faqMEDB*3{ZsbkZc&CAAx}CRW'
        'yEE?$5Y4pnwrqFiodu%VcHWll&b;S==zKeG%XVkpED&Yed0VzS^UeX$TqAE>;V#1V#oBhc04|Q{^Kg)Fr*Gaa|FlMb9S*Ly(>HII'
        'KdsT<goB&y^v&CG#btxg_;<z)e~f(!HTH9;uaBUxcGb%1jiiYFm#T63VNx8i0+&C-tG>XJ>-R}?9siILUVfDJ$0U{i`P7yel~q9T'
        '-yrLqpFrn-g&n&C_UlxwJLGa>*br=jjb(gKK{l3Yfm+nnHu`~eCI0#It(Jz0sUEpD#oh(w(YMKOn@;59I35U`j(4@6BD3&s-XQ8Q'
        'T^;}c'
    )
    assert isinstance(_MODEL_, _pydsdl_.DelimitedType)
