# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/runner/work/packaged-dsdl-py/packaged-dsdl-py/submodules/public_regulated_data_types/reg/udral/physics/electricity/Source.0.1.dsdl
#
# Generated at:  2025-10-08 12:28:10.180193 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     reg.udral.physics.electricity.Source
# Version:       0.1
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import reg.udral.physics.electricity
import uavcan.si.unit.energy

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class Source_0_1:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 power:       None | reg.udral.physics.electricity.Power_0_1 = None,
                 energy:      None | uavcan.si.unit.energy.Scalar_1_0 = None,
                 full_energy: None | uavcan.si.unit.energy.Scalar_1_0 = None) -> None:
        """
        reg.udral.physics.electricity.Source.0.1
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param power:       reg.udral.physics.electricity.Power.0.1 power
        :param energy:      uavcan.si.unit.energy.Scalar.1.0 energy
        :param full_energy: uavcan.si.unit.energy.Scalar.1.0 full_energy
        """
        self._power:       reg.udral.physics.electricity.Power_0_1
        self._energy:      uavcan.si.unit.energy.Scalar_1_0
        self._full_energy: uavcan.si.unit.energy.Scalar_1_0

        if power is None:
            self.power = reg.udral.physics.electricity.Power_0_1()
        elif isinstance(power, reg.udral.physics.electricity.Power_0_1):
            self.power = power
        else:
            raise ValueError(f'power: expected reg.udral.physics.electricity.Power_0_1 '
                             f'got {type(power).__name__}')

        if energy is None:
            self.energy = uavcan.si.unit.energy.Scalar_1_0()
        elif isinstance(energy, uavcan.si.unit.energy.Scalar_1_0):
            self.energy = energy
        else:
            raise ValueError(f'energy: expected uavcan.si.unit.energy.Scalar_1_0 '
                             f'got {type(energy).__name__}')

        if full_energy is None:
            self.full_energy = uavcan.si.unit.energy.Scalar_1_0()
        elif isinstance(full_energy, uavcan.si.unit.energy.Scalar_1_0):
            self.full_energy = full_energy
        else:
            raise ValueError(f'full_energy: expected uavcan.si.unit.energy.Scalar_1_0 '
                             f'got {type(full_energy).__name__}')

    @property
    def power(self) -> reg.udral.physics.electricity.Power_0_1:
        """
        reg.udral.physics.electricity.Power.0.1 power
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._power

    @power.setter
    def power(self, x: reg.udral.physics.electricity.Power_0_1) -> None:
        if isinstance(x, reg.udral.physics.electricity.Power_0_1):
            self._power = x
        else:
            raise ValueError(f'power: expected reg.udral.physics.electricity.Power_0_1 got {type(x).__name__}')

    @property
    def energy(self) -> uavcan.si.unit.energy.Scalar_1_0:
        """
        uavcan.si.unit.energy.Scalar.1.0 energy
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._energy

    @energy.setter
    def energy(self, x: uavcan.si.unit.energy.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.energy.Scalar_1_0):
            self._energy = x
        else:
            raise ValueError(f'energy: expected uavcan.si.unit.energy.Scalar_1_0 got {type(x).__name__}')

    @property
    def full_energy(self) -> uavcan.si.unit.energy.Scalar_1_0:
        """
        uavcan.si.unit.energy.Scalar.1.0 full_energy
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._full_energy

    @full_energy.setter
    def full_energy(self, x: uavcan.si.unit.energy.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.energy.Scalar_1_0):
            self._full_energy = x
        else:
            raise ValueError(f'full_energy: expected uavcan.si.unit.energy.Scalar_1_0 got {type(x).__name__}')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.power._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.energy._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.full_energy._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        assert 128 <= (_ser_.current_bit_length - _base_offset_) <= 128, \
            'Bad serialization of reg.udral.physics.electricity.Source.0.1'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> Source_0_1:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "power"
        _des_.pad_to_alignment(8)
        _f0_ = reg.udral.physics.electricity.Power_0_1._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f1_ holds the value of "energy"
        _des_.pad_to_alignment(8)
        _f1_ = uavcan.si.unit.energy.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f2_ holds the value of "full_energy"
        _des_.pad_to_alignment(8)
        _f2_ = uavcan.si.unit.energy.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        self = Source_0_1(
            power=_f0_,
            energy=_f1_,
            full_energy=_f2_)
        _des_.pad_to_alignment(8)
        assert 128 <= (_des_.consumed_bit_length - _base_offset_) <= 128, \
            'Bad deserialization of reg.udral.physics.electricity.Source.0.1'
        assert isinstance(self, Source_0_1)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'power=%s' % self.power,
            'energy=%s' % self.energy,
            'full_energy=%s' % self.full_energy,
        ])
        return f'reg.udral.physics.electricity.Source.0.1({_o_0_})'

    _EXTENT_BYTES_ = 16

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.StructureType = _restore_constant_(
        'ABzY8+F0gj0{^{OTZ<gW6&_i8u||$9p<EyrQY1#qCcC{h0V`LKy!Kko%JSkBu?d(~O?S<lih8=*Rn@aQ0fGDwV}*to)P4<40{H=X'
        '3xvFdkf->?KOm6D5b_U{ud2FdW-qhZfRh!g>8Z=Pe&;)<_rcPKf4kiAKh;-@Novw8ijB~cXY!}KpNS|=)TmHKT2WV@*|WM#Y^lYa'
        'Ng?V-_1e4j{km5z$2lKi|5+`DQJHF<MFmZaOiUy)kytGgX(!R1Ds_TmPsU@RjZ}F}ooe+*&GVyrr?YeJz53m{x)^hdOa0OcQ@;%b'
        '3rw4ys;lK~DYA5CQa4Vy<*{{k(i35kmaDIyZsD%l7rLfZy3pD}PeDIjY6M)F6Lq!Z<Amptkx`jTJCzeBrPd<1(O$wc-bg#Q(`lv6'
        'ge`Kb&~hZL9K)>(+nM6_aI`PReQD!N<U>pK4uh)+H#Q!r6s|s7eSWvS?yf~!*n7=wx%mF9ext5F8ym~>l<Ra}(EE@x;zM{+rcUud'
        '^TZ-A2Km}<o+0Ds4O*I?$B!TTK)q3yeZ*vij|!o2eJM^=Qdb=;^Xkf6I^+H%faQKoFVNQvyh%l&MZ&E}>xb3T@jxDkG%l33u}tgR'
        ')#ccD++ZUUalv70wdy`H*@vCGz~;fOTYZGsoZEzMQVxtOy3BKAvs&6$`d(dKDtK~_4@J7+V!lyKYI?cqnzE0;l^K9meW@t>84?JL'
        'l$o<<h9T^(gnZZ46GlR)%Q=J|&3auu6Y?HCA3Ya2O|^AFzY-HSu-=_<=^jf|!b7@7->xqCfP^~Bu^k|PR&^^4%tZACADq~#SSw|{'
        'Py?R<it9bPK`+u4y+kkL-!{EMH@#I$aX*7=S6dv;@Bka_(eHKj)Qi&I^56IHwLxTcK2}9tu|-16WYkxPD}wNv7%8CKVd-@Mg<GX('
        'xL%19lBi+g)ib+1O=Uhjc8CUU_jZ}V<;l@qNEq|16!kCa-VXb~^uaVm5LE9xS@z-XNan6&@W2n;!)ola&)w~AEDj2udosFR_D$bI'
        'dbN$T%N15mqJpm+p@Ol>ERgn}8Gx=fPis4jzCjUfzE985w@xpzB`3ZyhtqdZNbk`DL*IKy-@i>iI5FAuD*dopZOp3amP<ap?%_wf'
        '3(+>cFasIAxe!eBV|v?rLw6~eW{ajzS=dx<a_AkG6VmY9;Md+qj@(}714HAv_)o3&4h!dSkM`+{^h-J@Pw~1sk2*$U@NDlWBk(=C'
        '%N*m^)zhByQLE3-s?~?)tryO9IxlT8rP+-wmdRYO_983X9rjMia|@;wCStD$a1GD0$vU$n*g$2O+6VAh10QDOFlUL%$M^z-F<ulI'
        'Zhp7hWo&~v7ITz6JwCv7!v<Q7yu2ftO^MqRmJ92+jalUnp;e@;C!%4r&NwunQ@iq5i-L|<2Zu$qx22igmez=D5VVLi=;tgDa4WhG'
        'HWzxb7CdbYhLl_kxpN|_1E|iHfaTD17eMQyvp_4EBZtpzsoXV_{6v<iE(DT+$&O`Dl$IVxrUxW_D2!XZj@9e4)%Nh=<p#aWMVKhA'
        'RlmKXEYFzCUGude+I}<YE=a!2o4mH+Z*nj5djJ-)db^4DBG5GV8Yw3tr<LhWdZG0Kiu>}>X$Np0PX0#>xBL@@j(mvXKB2#!f#Ozz'
        'S!ZUr_Wb{e;O3DrHTBwC?0lzlgJH-p7~G6SX$t&50*ILkHOoh;M1Jut+`=Na4DPVLU>Ke<E=O&-&ShTauApZWWFa!@-XYZLh)>*I'
        '%w8f--6kl>-?WX|gt#7xO%gn_#CikJU?_Z$mMeWR@}-4$f%OK=TDb{rol!ZGDN1{t37gEJ)c5A8W-Z)^2crQ`nWr-GdhueAN)vQD'
        '=7oKk@O;@sLJK!Mi6#zUHt&rW?I=~N10Og8i!mg`O}M`4imB(!j050PySB!PtPIpA^0Cw^A0ZCDL<f+TClJyG#fKBhZt}6?bhp+P'
        'vX>XA5IOVJHZvNgwW&-Qhf%?v%?*DGCHy9dJcQcGJsxH6@rcXZt8L^v&zk(S7#IK_DRcM%ic#O(bbIp=*a#nMo2}yRHdJ}v_&uL*'
        'nIRfhd)8cM(nZ@f2F$)}AC{LUq)NMC-8jG;LJMbo%^fYd1OdZJuXnBU&Cb%ZkD^YUv2CAd^WKJZhH_xQ$ihdhN%Ub}`U?u^;+%Vq'
        'U_bu!N{Hh_7@88V(=<WY(YI1I^qn3ab`e3&!d}QmI_-@N=@9x*gGBE~Rk$}Q*4tAzPc0!7j;G>g+W8Y*rhm|%>0k8E(<UDJh<-)C'
        'rr+QdBmnmKP*eT!MsNTTYP?gSrTEAko-%rkH!!u-eKmD_{dlr{sRLHG)c!`n4VsY59Ex$qP@DHK@^~2Wv685WOmgGSh`|7w5f~t?'
        '8AtF=i^2pSO!f)02y8QA?Z2BWR+>LJd^)4W@58Y_EE*fme)4w<W(N9u7%=W)_3rTj<H&Mz_yJZQ96x+`+4Y?0-}yM<{Ol0`00'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
