# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2025-09-12 07:48:14.160601 UTC
# Namespace:     uavcan.si.sample.temperature

from uavcan.si.sample.temperature.Scalar_1_0 import Scalar_1_0 as Scalar_1_0

# Convenience aliases of the newest minor versions known at the time of code generation.
Scalar_1 = Scalar_1_0
