# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2025-09-11 15:53:03.478197 UTC
# Namespace:     zubax.service

from zubax.service.Heartbeat_1_0 import Heartbeat_1_0 as Heartbeat_1_0
from zubax.service.Readiness_1_0 import Readiness_1_0 as Readiness_1_0

# Convenience aliases of the newest minor versions known at the time of code generation.
Heartbeat_1 = Heartbeat_1_0
Readiness_1 = Readiness_1_0
