# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/runner/work/packaged-dsdl-py/packaged-dsdl-py/submodules/zubax_dsdl/zubax/primitive/boolean/Vector2.1.0.dsdl
#
# Generated at:  2025-09-11 15:53:03.643775 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     zubax.primitive.boolean.Vector2
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class Vector2_1_0:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 value: None | _NDArray_[_np_.bool_] | list[bool] = None) -> None:
        """
        zubax.primitive.boolean.Vector2.1.0
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param value: saturated bool[2] value
        """
        self._value: _NDArray_[_np_.bool_]

        if value is None:
            self.value = _np_.zeros(2, _np_.bool_)
        else:
            if isinstance(value, _np_.ndarray) and value.dtype == _np_.bool_ and value.ndim == 1 and value.size == 2:  # type: ignore
                # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                self._value = value
            else:
                # Last resort, slow construction of a new array. New memory may be allocated.
                value = _np_.array(value, _np_.bool_).flatten()
                if not value.size == 2:  # Length cannot be checked before casting and flattening
                    raise ValueError(f'value: invalid array length: not {value.size} == 2')
                self._value = value
            assert isinstance(self._value, _np_.ndarray)
            assert self._value.dtype == _np_.bool_  # type: ignore
            assert self._value.ndim == 1
            assert len(self._value) == 2

    @property
    def value(self) -> _NDArray_[_np_.bool_]:
        """
        saturated bool[2] value
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._value

    @value.setter
    def value(self, x: _NDArray_[_np_.bool_] | list[bool]) -> None:
        if isinstance(x, _np_.ndarray) and x.dtype == _np_.bool_ and x.ndim == 1 and x.size == 2:  # type: ignore
            # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
            self._value = x
        else:
            # Last resort, slow construction of a new array. New memory may be allocated.
            x = _np_.array(x, _np_.bool_).flatten()
            if not x.size == 2:  # Length cannot be checked before casting and flattening
                raise ValueError(f'value: invalid array length: not {x.size} == 2')
            self._value = x
        assert isinstance(self._value, _np_.ndarray)
        assert self._value.dtype == _np_.bool_  # type: ignore
        assert self._value.ndim == 1
        assert len(self._value) == 2

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        assert len(self.value) == 2, 'self.value: saturated bool[2]'
        _ser_.add_aligned_array_of_bits(self.value)
        _ser_.pad_to_alignment(8)
        assert 8 <= (_ser_.current_bit_length - _base_offset_) <= 8, \
            'Bad serialization of zubax.primitive.boolean.Vector2.1.0'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> Vector2_1_0:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "value"
        _f0_ = _des_.fetch_aligned_array_of_bits(2)
        assert len(_f0_) == 2, 'saturated bool[2]'
        self = Vector2_1_0(
            value=_f0_)
        _des_.pad_to_alignment(8)
        assert 8 <= (_des_.consumed_bit_length - _base_offset_) <= 8, \
            'Bad deserialization of zubax.primitive.boolean.Vector2.1.0'
        assert isinstance(self, Vector2_1_0)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'value=%s' % _np_.array2string(self.value, separator=',', edgeitems=10, threshold=100, max_line_width=1000000),
        ])
        return f'zubax.primitive.boolean.Vector2.1.0({_o_0_})'

    _EXTENT_BYTES_ = 1

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.StructureType = _restore_constant_(
        'ABzY8U+}_c0{?|nT~E|N6y4QbmJd-7qlrG?lddLI&>x_n;=>B8fcRu4)Aq_tXgkf!bloK(kq1pkCXs~e|MDk!r(HgEV>iuqdhb1R'
        '&fIhRt?}!3qgGySJ|Dy;P6B2?OP<Jm9wrd5NTs<l(gM2aEvt*j78<q(Ip7ICIm82OyC%zcO7Z#qBINxb*D{q>_8<tAN`Pm<4n$Vz'
        '=jg^+544dgLs4_Bo#FEdcIutl4?ILS#kjRvhJ^)#pK%navm|uQRS8LaPG*wD+;V0;L-$}rxz>Du?#`<0L;N1HT`QLTtIM*c86=QG'
        'W`|%SxSYu)_A8a(%Q#akl$IssHl&moM%-AIsu)n*cXzv|0KP1EO|dl}qEo4T$4#QijOAI(b$k)%s0iHzA>}-hc7UC0uED~@pnG&m'
        '^E{at+pBAIH&&#r#Bb4ZNY`CwDo6Kl6o?t5p-N<gZf*@yMTcOig&R3&PAxtcJ;ov-sV^dMw>KdNEB~E$jqMS4@q+Shtrtnc_26m}'
        'VfA=Y0RF^wr+#cgQr=*x%qr0-@B4?AKhPrKRM4sW%-XS`qlSLYv(jbjMd(XK(={tNs*M#1sUg|c&0TOF3kQ{@4^X@nvxZt2L#`p>'
        '7GgYdH`y2O9F{9>nT&DW%`&439RURrU^%A-xt9M+WQcB}OB2-Z`nM;fx&Dmy7Rryzm@cvmG_AiXy@zgw+PTMfAztvuzmN}5Y`aNQ'
        'grzu|2{%~|8S`N>f4QIyE|{=2oH_y<&Rwt+ECywP^?sUTf*azfy|u~9JsANWiB<8=&6KjMna?QfXR!UBU0SEp4enm4oLR-RQnti0'
        'B#3Oj(H33tL2QaGu}!~^Vn=-PWW;0fv~03i5Q~*1Dlc?-9LsF?FT+rDi9REF6~@jub@XLtT)d)tnPA=w+Z_A>cLTyM+XMgr'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
