# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/runner/work/packaged-dsdl-py/packaged-dsdl-py/submodules/public_regulated_data_types/uavcan/file/406.List.0.1.dsdl
#
# Generated at:  2025-09-12 07:48:14.357699 UTC
# Is deprecated: yes
# Fixed port ID: 406
# Full name:     uavcan.file.List
# Version:       0.1
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import warnings as _warnings_
import uavcan.file

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class List_0_1:
    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Request:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self,
                     entry_index:    None | int | _np_.uint32 = None,
                     directory_path: None | uavcan.file.Path_1_0 = None) -> None:
            """
            uavcan.file.List.Request.0.1
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param entry_index:    saturated uint32 entry_index
            :param directory_path: uavcan.file.Path.1.0 directory_path
            """
            _warnings_.warn('Data type uavcan.file.List.Request.0.1 is deprecated', DeprecationWarning)

            self._entry_index:    int
            self._directory_path: uavcan.file.Path_1_0

            self.entry_index = entry_index if entry_index is not None else 0  # type: ignore

            if directory_path is None:
                self.directory_path = uavcan.file.Path_1_0()
            elif isinstance(directory_path, uavcan.file.Path_1_0):
                self.directory_path = directory_path
            else:
                raise ValueError(f'directory_path: expected uavcan.file.Path_1_0 '
                                 f'got {type(directory_path).__name__}')

        @property
        def entry_index(self) -> int:
            """
            saturated uint32 entry_index
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._entry_index

        @entry_index.setter
        def entry_index(self, x: int | _np_.uint32) -> None:
            """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
            x = int(x)
            if 0 <= x <= 4294967295:
                self._entry_index = x
            else:
                raise ValueError(f'entry_index: value {x} is not in [0, 4294967295]')

        @property
        def directory_path(self) -> uavcan.file.Path_1_0:
            """
            uavcan.file.Path.1.0 directory_path
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._directory_path

        @directory_path.setter
        def directory_path(self, x: uavcan.file.Path_1_0) -> None:
            if isinstance(x, uavcan.file.Path_1_0):
                self._directory_path = x
            else:
                raise ValueError(f'directory_path: expected uavcan.file.Path_1_0 got {type(x).__name__}')

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Serializer_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.add_aligned_u32(max(min(self.entry_index, 4294967295), 0))
            _ser_.skip_bits(32)
            _ser_.pad_to_alignment(8)
            self.directory_path._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
            _ser_.pad_to_alignment(8)
            assert 72 <= (_ser_.current_bit_length - _base_offset_) <= 968, \
                'Bad serialization of uavcan.file.List.Request.0.1'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Deserializer_) -> List_0_1.Request:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f0_ holds the value of "entry_index"
            _f0_ = _des_.fetch_aligned_u32()
            # Temporary _f1_ holds the value of ""
            _des_.skip_bits(32)
            # Temporary _f2_ holds the value of "directory_path"
            _des_.pad_to_alignment(8)
            _f2_ = uavcan.file.Path_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = List_0_1.Request(
                entry_index=_f0_,
                directory_path=_f2_)
            _des_.pad_to_alignment(8)
            assert 72 <= (_des_.consumed_bit_length - _base_offset_) <= 968, \
                'Bad deserialization of uavcan.file.List.Request.0.1'
            assert isinstance(self, List_0_1.Request)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'entry_index=%s' % self.entry_index,
                'directory_path=%s' % self.directory_path,
            ])
            return f'uavcan.file.List.Request.0.1({_o_0_})'

        _FIXED_PORT_ID_ = 406
        _EXTENT_BYTES_ = 300

        # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
        # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
        # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
        # is not dependent on PyDSDL.
        _MODEL_: _pydsdl_.DelimitedType = _restore_constant_(
            'ABzY8KG4Hx0{^90ZEqb%6}A;Ov2R|QG&BiRw9^2IjqJ?}2%&tcNgG;j>=?%lkq~U>?w)&Rl--?WX4lsjfk-7@f>?=&EGjQ8@B#6K'
            'FGxrgLgG6=i|5SleQ|6HRZSH8-kCXP&OGNi&z#BQh2MVVr8)nndMzKtE>42bk<~KMKa{<Mf-o{^Zk#Ttu1>#6iB9n`-WlaoKdV>X'
            'uYX)GSI0x0Wn^nLSDn6J*fJ_gOZ%6+5N0xki%X^4jbs+|HGJRIt_Zg22PL_pt`@^xvQC?f{hWBvetuSW=eqMhuivk$lc6jMt9xZZ'
            'uKpgJ9ue_mRb9PsM^h3{!{~&uEM!=4Y)6^rmd~hnvEux@nbU)e;&-xw24wf2>15c`MVL@FC{*1Qa2`olgsF+CR-dgdY>geUS#TS3'
            '8$87)`dPhQSDy)8A+uQ8c-GOAvZp%LNy-X40<JOb)zv~6o2ahlYRsLlPHo9J*4beH+0>=#bB7;j*XS7VKESWp1E^QK!eK9URb8nr'
            'Z4-=kDHeTWMZe?>iqcWQTfRKrL7iwnb*i(oiQJM1T%A&9y7S#R&Xqcc{7mhtSB}V(wQ^Kf7avHBV&txeV4X+zLw!1=gi>JAq)xrk'
            'dVaOLs9sZFP+tUU)e`W}Wu%Ky-Oa0)T0p}-!*r<K>)m-yL}R@W_7YcDSH_V}Q-Yw2=fBt0sc-0_iT6IfwvkrHLX+2(ILe6|r9G2q'
            '<nsImr3N?@Ao;zVtSpS3t*A(8Bv*aAdil1=B3V#&=u$p3ue6kLNnrhpn`M$nJ36rPc(^N*lImaA%iYDN$o%~lj0do~xGl2*ZBtH#'
            'J}RU~VJi0kEeyWjFi4JldHhnHf!h25%QhY#t4?q&l!?UB?mRD@d+Janw3o}w7x!k_BLtEn8`;K_W6I1dR2H-B8Dv|?J;AQ1tG)mh'
            '0ST8*F+=`CDFM@^`)_TnZ?Es%+xGTKR-Ydy2XR<(9LT<+U)=Uc%Vbh0vRdj}8Sy9>vUsQc%$0nNwQ0NdaSs1qES-(@hvD6~Hov*^'
            'b{mZPNxOskX*Zv`qU!vN)`h)Mqn_-tRJYWR)Smj4`b7x^iV0_6dc^gU>I}HPM{$@NTZE|j&FWm}OlczuxlBWkVs(OlCAtUhY(d!f'
            'eDOX*hUc$AX_R4^K5k2|=+(l|*hh7B7IpPV4k%t@=+^R4tv;+euI%{)Lyl45We>y-Ee()y#4}Y|%pPyl0{%D<+$6kda3i=Lu)n%s'
            'IXoXK=@6skGG{T;5!Js`S0288Y;JB7R|Ld~-36U>!Cr(LVJsDV96?zGZH<M_#Jf9pz8;7jMZ#psNPzS@7LMSU2`#h}1?C`gLnyCs'
            'iF8U_zIK`2I;bi;_G8N!ToIP~xQRqzyp=Vk5U~d2a5WOkJeHWq6GoW67%Ckp-Xf;H#=RkWBX8%m)vg4cZ2~x;S>qQ`lM~An3<7aE'
            '2(TSaFEZYvwa5M7zoQ(%PljMwCWSKPK*2FKO65pIii?-e?oZ~$8+)Njc7Y|cRxGm<%5dt4;+0z+A=bot16^)37G(oIqim1`Oj0B|'
            'd&FZ6*4Q#>LLr1S)G(A&RD+`(PSJu_KQeYaooT%v?zzLMgrw-SY?Iw6s_?xCgB>a3C==4bu&^?wHPi2l9u-5vFgGy3yr&b~42}Po'
            'D4*Sa+_N~wyTc%Y_O4jNeNOB#b4XUZZ9}ce-ZyUCM3PaZt8MaSl9-|6UlU72XtF};j6soOmT9kH5p}>Df2=0g!eD=FCM{CRHH71p'
            '*(2Aa0()l6#i0?m*EhwTHwBa_B^RJZy+}0uT86wgJ<{`)x8Td2s*7F?!oq~iX>aOK<hUb0SXRGNzgK@ye^ejh??>uS>d#!D>RW1~'
            'QLC+eSI3KOJ96O4!0ZmXy1bdLyNl(1sh?H&Gm~tDGg?pTDf{`7x}g50ZkFmdPt>zbb$E#CFV(rPUjJItR9=U+Oq50a^$AquqlLM-'
            '9j=&GS_Du5N4Uv}8QTPQNRGv|T+oypt56XVz8m8r#Jq1;TUthm#?+X<n87NNk!lUNeapdWd`sX7oih+(5?q~W@2(<+CKcC3iK<C_'
            '2}6I1#zoNij-sZn{bKA7_ta=uR;E3K1pc($ksE8kO!!mz0rx>lOME?GSn>~O5Lny+?OZtt8=_?i_0aG&6O`tt9HvNnY~NCenKJ+Z'
            'COqJjc@9iGqOdeJ#tv}<F5;Zl92@J2_{k(!5(TRxxEYPjpkcfl?cu%^4pDPFk!2V)gvG#|1u4Z<iPNF{6T<-m1qh}!yE<-xatOU~'
            '${x7G#nt6FlbpN>ACko3fcJVHt}#Mj3`fs~#xtCy9)tZ7tviG6BhE~=2J)vmYV?7fA*L}bL)LY!bAx^ZjjlioL97a~@3vfrYadP_'
            'K`7p435N+`j}tGYif=m05hSBPY)OC-;i9$7tB6fvPB4e8kOG3_>ptk5(U57EvU3Oy*}`9vh3V|0$wVw!SZ1*CnA~Dlo`LMBao=RP'
            'M^mQ_om!T9>=-#SL|FLdY1wHeP2(-2y<%KWtFt4_JdTogTjpF5$Sado4kI<TiNlGZ=We_G%7on127<D69Uq5Z$T@^l0%Dr%b4l{m'
            '>#=UrK1O;~koIznlE6dI*ftmKMs1XiueRQ(gX|TuVX3d;1GMpl&Qm=a;K|IB%MB*iSAtso?NGsHK||LzekYUq`zMs>e@;G4#~wDz'
            'zRPchPq%XRDIoY+@o{(F3%yVo{*871z`CaKe*=r&m@fLby(FF+{ztR;ZCoAyJ$7*QbK}jGqE6yLdbW9pUQl0FH$T~BqW(R(I@EtY'
            'eP-|$0=ZFA^~QTk)dlqJ&Htp>P!Spyd*FR4@Njsic{m)J)Y-HgNWpYjzx|{)R_70Wx2bd!=)Je(-(HKeZ!eEIPd+|ml1+pE0nxU2'
            'z&;WH00'
        )
        assert isinstance(_MODEL_, _pydsdl_.DelimitedType)

    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Response:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self,
                     entry_base_name: None | uavcan.file.Path_1_0 = None) -> None:
            """
            uavcan.file.List.Response.0.1
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param entry_base_name: uavcan.file.Path.1.0 entry_base_name
            """
            _warnings_.warn('Data type uavcan.file.List.Response.0.1 is deprecated', DeprecationWarning)

            self._entry_base_name: uavcan.file.Path_1_0

            if entry_base_name is None:
                self.entry_base_name = uavcan.file.Path_1_0()
            elif isinstance(entry_base_name, uavcan.file.Path_1_0):
                self.entry_base_name = entry_base_name
            else:
                raise ValueError(f'entry_base_name: expected uavcan.file.Path_1_0 '
                                 f'got {type(entry_base_name).__name__}')

        @property
        def entry_base_name(self) -> uavcan.file.Path_1_0:
            """
            uavcan.file.Path.1.0 entry_base_name
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._entry_base_name

        @entry_base_name.setter
        def entry_base_name(self, x: uavcan.file.Path_1_0) -> None:
            if isinstance(x, uavcan.file.Path_1_0):
                self._entry_base_name = x
            else:
                raise ValueError(f'entry_base_name: expected uavcan.file.Path_1_0 got {type(x).__name__}')

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Serializer_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.skip_bits(32)
            _ser_.pad_to_alignment(8)
            self.entry_base_name._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
            _ser_.pad_to_alignment(8)
            assert 40 <= (_ser_.current_bit_length - _base_offset_) <= 936, \
                'Bad serialization of uavcan.file.List.Response.0.1'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Deserializer_) -> List_0_1.Response:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f3_ holds the value of ""
            _des_.skip_bits(32)
            # Temporary _f4_ holds the value of "entry_base_name"
            _des_.pad_to_alignment(8)
            _f4_ = uavcan.file.Path_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = List_0_1.Response(
                entry_base_name=_f4_)
            _des_.pad_to_alignment(8)
            assert 40 <= (_des_.consumed_bit_length - _base_offset_) <= 936, \
                'Bad deserialization of uavcan.file.List.Response.0.1'
            assert isinstance(self, List_0_1.Response)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'entry_base_name=%s' % self.entry_base_name,
            ])
            return f'uavcan.file.List.Response.0.1({_o_0_})'

        _FIXED_PORT_ID_ = 406
        _EXTENT_BYTES_ = 300

        # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
        # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
        # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
        # is not dependent on PyDSDL.
        _MODEL_: _pydsdl_.DelimitedType = _restore_constant_(
            'ABzY8KG4Hx0{^X7ZEqY`6<#ZDVsD!_3`qe&FQ!6k$sQ-Ds(2AdCW$H9cw-zlDpJw(&dk}p7th`q&7JXjBOy{GDkBD3ktwC{0r3S@'
            's)U4)_*47=KJuJ9v)<igEkGiXwX=85dG5K-Ip?`&pDcg)&nqqWuY4sPM>dK*-%_S!tRKrDCeII(VVYQ-Q&nEROR*l}F*+QlR6VUW'
            '-mQLGb;^srHioiFwaUv6^Q;K-BBObe7knd!fcShNk3(s^z6SPvZFBE{Y?>I0cPsueWmYGKfi692o}X6TR(I*W>fNe*(U*Ci>7dBT'
            'RzC*nIU%1}Rpm?jGK#br>}ramX*g{^lDYJAj<Nj0VwB@VM+oW>K4#B?C<2}PF_}TGs;;nsYL~65T=t_Rtjd>h9?Fg>68$6-{er0w'
            'g(a^l0<~7YFdv9|SzT(L+U2!bZuTY6)l2G1cd6Ur)2r(^vHI%7ul(XUXU{S@uF9K_Bv!F<-^IDZtMeJT>{CobGI_(oIb5b0XIvk{'
            'V(m?1^}tZ{1C!H$vN=5U<?ae-4W-TfVG>cLUMp|xPn_A*yMuRo{EAchi|U{%KkM6Enn-5RET^YMP_6<gm7&hZRW~g^)4cNg%w8R^'
            'dVRXF`lkAJcZng@ciDT{4`N%DUz;3h3Xap|&wfXhd{5^!Q4jHTlIRP5l2)ZS55$g#K@w}^d~J`02?)zkuMbknWS(TR-4QB{oU8lg'
            '=k6pXlsTD&rhI6&%*b$c!~SZoh+~<JpR>H^AIrF)>iw$IUHJed*lWo6A-rxLNHd@VN-5Xpg>>W(<q4>T!;jpedV7N9_#0}2B=G~x'
            '_MTiQFL73jSi-cs#HOteEb>h!sWh%ndqqG9L?Ih`@AQKD$&8^I;w>Yi%9m4D*+RYI8e#>Ma1rFQJu#o!@3^GGb@k!B{hfoI!v_b>'
            'U%g#^X_6eok&)#<=1O+uz%ec32|9dM`<V=R6&13w+dOkkZnMlBR4&f!KgH7C+j+~sf3Nrb!#A2>)Z=Cc^|Nj|g`#q8Mz;K5Tq_|%'
            'rfO4-lvVGkpBIpoh;RljkEl8=ub|dXDDu-J%Y6t@ue|Qtq{u?@Ss#4IVtI)_VjZA%_94<IPBoq)!%N#xB$cq_Ud#%o&gJqb$&RY>'
            '8v5!;4k+4U>bBBxr9LX#wg_B;p{$UWB0ypL84Zwe#4}Y(yuDb<6!16@+zPy@ciX$=F<zB(W3Ty2TEv*KzOWwZkg8uQ@zz%^v|2r~'
            'z!VJUwRZ%g2s_5wQ1EdCnGh-w32nrihr8eK#GxXQn0PEu^g0rj0L%p~v=uqtL1{<O5Mg6!l~~_iXIKl>XJEJ1!QzI<sE<oU<cagj'
            'k|Y<A2IYVniw>{FN$3hjBz-YbI#j$xM12j_6T#T|IeE`Ey!HWs9F$p&i>S$p4tWDlta~1|!|8?LJsN)~o%@b<M13*^9U12;DFzC_'
            '*k~xnB2?VGe0Fy-cYk0nbjdNe<f;`N1|fq}hZJpmt1ZNq*r};Y6AdFX;4{jaS<oa!tj!Ux)m&rCxDJI7(n!NmPFeNN2b{76RJSq#'
            'p1x_&7bCYhm5>xYEShB3iYnY(!DNRjv1Ej_aLh9q(N@y$i-7VGVVQ>!a31IwH$#md5v8-+Pv#HHe7BiIl)cTja5E7j8jEB#+t#IZ'
            'w)gGZUq_PBrJGIiWgI6X%O7W+h%hm^)P_lslPc3r!$NAKZrrizT#E$zV>6i{rQAa}USW=GoeJz}xE4o=xU<s}yLSbYX-L*Xk2;a4'
            'XD@@i*W=E!oww}Toywa|4g5Uuxu%_~MU&%>{B1`)h1h<mey2Xd|KF>R)gQP))jjn_tybN+tK(`jE<JZ;;OzqpXlebr>aG;?Qa`Kk'
            'R}pYF_5%=JYaROjUrVhPbIpr_7rDb+7fyPIO9pP6LVM(GV!dgurdt!JXEx2V=PK!$#hQ8~l1p2gFfLd|01)zkiLS-=CK~AonQz}4'
            'rYIrZ7q$phy|;)Gs-5YCN7HtD7j;f2a+t=n3BweVFmX8OY;7kUw!Ym@lI=id_<QUH+N^tmM_bo6h;kaAD_CA~flmF_YxQwj)t0$4'
            ';ReDUNm^fEkdt~{n}|-tEnuN4GeW5wvA%d?%REnap98opI;;$4+*W#k18vL!N+Zbe<5IQ0zR6yiwb4O0NFf>n{6p&DCqu<#H<35l'
            'jhRMFzNCJI8u`0=)v8~gs^9d~`wL4`{jt3M+O5~?9|pH@r<~m=>QATcmi_a>K45#k>?c1ZNd4u1Ed9TpJx$jh)@F}*7F%RFJ2(j*'
            '!v5B@g-{xQlde#o)^kw@&GN~#S<bAVS+AQ&y@=WWT0QgMP_O>i{HcHZf7!y^M<*Cq^J?#%)$#^rl=>H7<|~3YXV1;z0z=Z>dPrJG'
            '^em~*5jZuI%~Q0uxwLRbRjLQx-dS~X=F04x>DcC%PZqpnSMT2iZe&;X4gdf'
        )
        assert isinstance(_MODEL_, _pydsdl_.DelimitedType)

    def __repr__(self) -> str:
        return 'uavcan.file.List.0.1()'


    _FIXED_PORT_ID_ = 406
    _MODEL_: _pydsdl_.ServiceType = _restore_constant_(
        'ABzY8KG4Hx0{_)m?Qa}M8MhTTxm;eHG&Bi~LI)SMXX30KKot6gnzW(lV#jiv5QM7D-0s}X*n7Ln?5@ujQ7MrCCDKYn$`*=5f$}1O'
        '_`(+?qzWPNi9e})<M+(Wz1TiC3Y9=4^1aN?JoC)&`8~hqnY%yp-p%t<=3n_z+7GiZ^88F_#Upi(w<6*BLDEf=Oy!~~kKGh{TLogH'
        'pNi^9HUFS`w`!Cpd@a6Th%EPW8kbY$i8n>0x>yqKo_W|;aV)f%ax>ROkQaK7vFH4lcd^y^f^P>r_Sy<QTvu7{t=mnivgU6Kov9=y'
        'J4bH2&rho6RCD^r)dRTc^E}t8RpcV8-ht5rPBxrXmCs#MA__-t)cug>+#cwl<*BAKs%^|Tb1TkNCl=wi<6Lxv-hHNHeoN(kB;rmk'
        't0sf-fCH^=5(2Hym1oxmhG?0070*`a5uNBq)p}Ka#?Nvdhg^r_h8`9zIa?kRajyHoH55BlIpc>(P?b{^o}Dj`ukkQcacB40<i+yE'
        '$p_j_R0w!)<8Ax^^5rJWu$Nqrm&)_&0*kgq$l8f!?Sdl6icEO4<%@$I<Z<_DwmdZ+$Tbef<!O1QIo+J1Sjn@9&uCqF;ebeK&HGh('
        '?l#9LMy?wOmT7b^7eyqxz{GKpIm<6MYw`=SA?JZwc@+4kJWzSRYNqA$4p6^MFil+dN^_b5VOP)itthL?R|cMrLIS7rz2B?y_%~H<'
        '{k@5=&eQUcpQKgE4l<JUyR9Trh~=3T(M^Cu4wBzUh30vp$1^IB3c;1P%NMRDalmsCPn=4JrkPsAloFUfyIMpM*ZqAn5Bu9ZDn#{@'
        's?n@HM&$1}FusRX=hk`L5$hrqxjM+DEx*fm04){-mO<@-ErVZI#h^BQz_gY7hsq<A3q`~+wK+{wrygg>60wu=*d+IA(GqY(BO2Mt'
        '!$UG3n<#sDN|r&knbZ*Ml3XwePy-~CI{6s+CsG1SkKTN1ZFzlp<HovKFWcqCL2%%Q78yCRE9q<N25BA*6Qx}qZEGITC>T<^<~~y<'
        'FOoK`SH{mDJk6K-%JLom`dh2t+IZVJBY)_2kdK<_$doA0jA@<U>Ra_BllSB|<OBJxd@RcX3KR;Qf#?xd56hF_`i=<wG|{<_oL?<Z'
        '`&m-xK=_oVzCp1(LT{03fjes`06QjmpCH21i%=SwkW3%eg;Df!rkCigsyv0f+TtA%UMA=+r~OKPSk|+mWdaO2MurzH5F0h4gNVbQ'
        'k<#MnVXGFfM~+nG3EI@V;w^b(ugXad&-jvO@KIBmXSO0$kL0C0pFcD;wTcn}aUyeGeVLIJmh~~#Wpo@S;sDwjG8MC18`r+(u?;C$'
        '5=VUo(yNeV0)~muOl2&`Gss*I%FD8dXOhh=&XL&+s!E2<SObIeOp7)u5z7;^N+(IqLIucSs?QoU7A1ip3`^RqCsiP6i%_%`>IQ4|'
        '%{rs4dfuzA3xETfS-bFBWUL{)j>qOa58L7NET%o&dejH=9q9;u5(Et%<uWNc5{9u+m-ks9DS7Ga=43{^u@|yr8(0!+S%Zv-7^e<I'
        'IRAQ`vCC}PLYF2Alj07Yky~T|6K9c%w`j~_jV&YVihxT!g@t^Cs&}x#5n8ZnMh1pQPn`A1mg^KsNQ&wfF4$I4ndwCc>_8@&h#AkY'
        'FxNa3my>pzwM5<%7^X%Cn734f%3$q>LZsu{4|<l2@U9bxpnaBKMm-l~G0qSyx2>htaPKQuzJwqnOBY=5c@!nRjNXPT;b9WzT*U+m'
        'AFxar4GTmayfMeJv1SSO$7Wn3q?AKAUJ-9)HWb)1CNB08c6E7`U3-&3nYtqLkfTN<Y+n~6?zTtTn|U)P-9>rMsDYm+K5^PC&5-1%'
        'k-uoj59BZ9ujH@ghxq>+`CIurN>F)2u3NRbwX1Z@x^`q=$-vX^qN_{o<EmLJc1!)Z!k-*Q!ynUnA>SiAUz8W*-{fnB{MkeK{;K@>'
        'L>J}n%hO+3`l@Xzm!K^}Ws!e;2o?EYW@>7KGR8>@11jJMH8~++8(|%SqfwS~F(StTR75b-jZqRZ*AqKh29d&}0e|rXvjh*MTR`nw'
        '3RdG=1WV|gfe?}4)v@;ORfI6<vL#j^Ya)}v(4X9z@ao@@!sfM^jQwF=SPhGdZVN7fKdw8<1{yHt{z!hneUMTMDi0Xu^a2e6i|e3W'
        'Rt(*SXla3buzZb~=%&aVqKG@TX{p%Q8Gry09&qwB1ttbjtW0!>9YPB({2b*REmlME<54O(5>^E;(;qB@hS6?f2lbX^@S6MyG{LAK'
        'ED4sAAazkHaXO@bl#s(f0fMQMZ52A8GPrJyk_GB;QMxjUBn5BChbYQ$z#A<C*8m|fhP<bRiD5WNJqFtaT6Y57cpNA3WstwC0;>;X'
        '3_cBD>5;Beo+s!x(C9L>5Q0=8G~HHKr`(58NDz|OP9ZlT>|tc2R8pnW<U!Q;*ct~I0Sc`qUInxyqyUr45+M+feANb>W6>kpb;&pc'
        'N9f!X$vmm=qRCJ!Nm$0PF_^qgrVIngkTq{3+!7<BmQIeP20KD7>A@|0GqkMRhl#Zoi=BLsP7C8B#60qnc56_q1jx&y1#+XCXzNGD'
        'dWO4h`}rZcg>wXHo7IgUW+KH9Mg<U4LhlKZ$zFrC3;O`+1tye{W26Kwf{Avqa2q)<Gb(MZejU-vxn-%z;(fF+iB6ANqJt|lJ#1J^'
        'mgc=m{%N9Mlc1q%8{CtH{PQzP^k0XcMq}^TX?N+)@ablbUj-OlD?VyY8=+@1!{0#X_sz47{~MU}#%R(<u1M?|{)?UbHcH1o5AC15'
        'XWW()c?uWO7wkp!f?SlZJzFu6e;<|(`HxQ@8Qg_HZlqMTa`$L?7Ja+@B}MyEpkdMb?xzeFhgExVm>AUYu<Q%LXxf(h6t65yPrSED'
        'y$ba19yNEb+W6heU``M3Pk3mqd?$UUSHih}#O+oe`=Q{o6Mpfri>gt8yy4a9%m49j6JN(>v$iI+(6`wu6AJ&w(^UA8bJWbmrV_MW'
        '4!aiIl`;s7C%grWyB^&&{YgRPWvG?5DD4@v9h|ZSNyR}_gjOO+n@u@sL0)<)L<3oW%hXe-*;vgTRx`1qOnY$+XGP`frjb~{#1y4N'
        '3=8(4QJ-6EC&^-qYy92wS}LCN*mWm6y9M6#y)<MT9j%+Qml$*9sXOTuwiqR;y$8?l*7l`=)RIoKxyc)wiaXkUmw_ur)p^{nOVz=F'
        '=64y~)o-x5xdmFK0`5#ZOHR6RV{{!+IP}~_m(-USV$y!|C6HkAB3`m*$oqv)%=_Aq$NwEko*=ZfNkZ$yvVqL~!vwM1Gj7Fl^DLkl'
        'rsL-M0b2iS@IEGG`q%%LEbjer)EsyubtA#5VdfFn01bZJ8a~~8o+2_^*7Q&<$F4-1Z3;<9FN$6|c(E02<)_n64bP*e)wEBFNzwBD'
        '4J>*zR9+YW00'
    )
    assert isinstance(_MODEL_, _pydsdl_.ServiceType)
