# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2025-11-24 13:46:53.901842 UTC
# Namespace:     uavcan.si.unit.angular_velocity

from uavcan.si.unit.angular_velocity.Scalar_1_0 import Scalar_1_0 as Scalar_1_0
from uavcan.si.unit.angular_velocity.Vector3_1_0 import Vector3_1_0 as Vector3_1_0

# Convenience aliases of the newest minor versions known at the time of code generation.
Scalar_1 = Scalar_1_0
Vector3_1 = Vector3_1_0
