# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2025-09-12 07:48:15.248995 UTC
# Namespace:     reg.udral.service

# There are no data types in this namespace. There may be data types in nested namespaces.
