# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2025-09-11 15:53:01.615467 UTC
# Namespace:     reg.udral.service

# There are no data types in this namespace. There may be data types in nested namespaces.
