# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/runner/work/packaged-dsdl-py/packaged-dsdl-py/submodules/zubax_dsdl/zubax/physics/kinematics/DoF2nd.0.1.dsdl
#
# Generated at:  2025-09-11 16:20:11.415923 UTC
# Is deprecated: yes
# Fixed port ID: None
# Full name:     zubax.physics.kinematics.DoF2nd
# Version:       0.1
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import warnings as _warnings_

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class DoF2nd_0_1:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 position: None | int | float | _np_.float32 = None,
                 velocity: None | int | float | _np_.float32 = None) -> None:
        """
        zubax.physics.kinematics.DoF2nd.0.1
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param position: saturated float32 position
        :param velocity: saturated float32 velocity
        """
        _warnings_.warn('Data type zubax.physics.kinematics.DoF2nd.0.1 is deprecated', DeprecationWarning)

        self._position: float
        self._velocity: float

        self.position = position if position is not None else 0.0  # type: ignore

        self.velocity = velocity if velocity is not None else 0.0  # type: ignore

    @property
    def position(self) -> float:
        """
        saturated float32 position
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._position

    @position.setter
    def position(self, x: int | float | _np_.float32) -> None:
        """Raises ValueError if the value is finite and outside of the permitted range, regardless of the cast mode."""
        x = float(x)
        in_range = -340282346638528859811704183484516925440.0 <= x <= 340282346638528859811704183484516925440.0
        if in_range or not _np_.isfinite(x):
            self._position = x
        else:
            raise ValueError(f'position: value {x} is not in [-340282346638528859811704183484516925440, 340282346638528859811704183484516925440]')

    @property
    def velocity(self) -> float:
        """
        saturated float32 velocity
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._velocity

    @velocity.setter
    def velocity(self, x: int | float | _np_.float32) -> None:
        """Raises ValueError if the value is finite and outside of the permitted range, regardless of the cast mode."""
        x = float(x)
        in_range = -340282346638528859811704183484516925440.0 <= x <= 340282346638528859811704183484516925440.0
        if in_range or not _np_.isfinite(x):
            self._velocity = x
        else:
            raise ValueError(f'velocity: value {x} is not in [-340282346638528859811704183484516925440, 340282346638528859811704183484516925440]')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        if _np_.isfinite(self.position):
            if self.position > 340282346638528859811704183484516925440.0:
                _ser_.add_aligned_f32(340282346638528859811704183484516925440.0)
            elif self.position < -340282346638528859811704183484516925440.0:
                _ser_.add_aligned_f32(-340282346638528859811704183484516925440.0)
            else:
                _ser_.add_aligned_f32(self.position)
        else:
            _ser_.add_aligned_f32(self.position)
        if _np_.isfinite(self.velocity):
            if self.velocity > 340282346638528859811704183484516925440.0:
                _ser_.add_aligned_f32(340282346638528859811704183484516925440.0)
            elif self.velocity < -340282346638528859811704183484516925440.0:
                _ser_.add_aligned_f32(-340282346638528859811704183484516925440.0)
            else:
                _ser_.add_aligned_f32(self.velocity)
        else:
            _ser_.add_aligned_f32(self.velocity)
        _ser_.pad_to_alignment(8)
        assert 64 <= (_ser_.current_bit_length - _base_offset_) <= 64, \
            'Bad serialization of zubax.physics.kinematics.DoF2nd.0.1'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> DoF2nd_0_1:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "position"
        _f0_ = _des_.fetch_aligned_f32()
        # Temporary _f1_ holds the value of "velocity"
        _f1_ = _des_.fetch_aligned_f32()
        self = DoF2nd_0_1(
            position=_f0_,
            velocity=_f1_)
        _des_.pad_to_alignment(8)
        assert 64 <= (_des_.consumed_bit_length - _base_offset_) <= 64, \
            'Bad deserialization of zubax.physics.kinematics.DoF2nd.0.1'
        assert isinstance(self, DoF2nd_0_1)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'position=%s' % self.position,
            'velocity=%s' % self.velocity,
        ])
        return f'zubax.physics.kinematics.DoF2nd.0.1({_o_0_})'

    _EXTENT_BYTES_ = 8

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.StructureType = _restore_constant_(
        'ABzY8yY|9p0{?|n-D?y{5Z_?Fj2|&XJ-mm@fDq$@<Hw77mpes|ysU{KiXvXF>7H)4n#^>M{js+j5cI)Ar9mO>-y5rEH|}Z-&azDP'
        'RMl^)e)X$)J^8se)oQM=RQI{%WlpRxl9qCpvQp%v&{eIibRvdRkDT#^^F}=G*COu4%WvYVxDuv_q80j=c0HrLyoSD&h0S-Q5*2mH'
        '{9CWxP&|fN(iO%^ts=C-%#)$L7u&7&#Q*V43?~S6&Pe8+uyGr)kErTvR18yVQj~mD%^cy>QQ}gGN2S+BR?^8XMjT%&HFe)Mbb>JH'
        'NGVjuL2PFTSy1aprMZZ3Hk{u)NKa|`ee|s-SL)+!+=}5Wv5qQE4Ic-3hd34ODCs;;FMeTY;jn*;ysQmv#Q3n#8o&1U_ZxDyqGvD_'
        'W}9K8$S_H`E@EgU$C*Lpun6ae)`fNkzrt^@^bRt(_!H2sD0LxSKf)zg@l1rpu{jXd9}GCbF2e#`h07i};-WU9piXdX?KF8IdxDc%'
        '8%HFM8)1Q1?M)%jQ3_I1WFX9>TPYcKzlnYHHq+BRWPIW(_5(VpXxezCgu(NF+U&$|rl!RX?FfD)P4Y^OMXrW9>lu#2mnf4k*XWKU'
        'H_D+oq*o1Oi0+XPW0)UEF~62y&zl672DV6mTCC9s<&spovJmk-TnhKrbyrmQG^3?fos6oC_N2|8SHcOiooSO9?PwZEMw#|*6k#Zr'
        'RBh+jK||kQlN4eNl>L)Jr-wTu!Y>VZ#A#x*b`6$APEd+BSKt=hhTq{2SjFF;@E6=^`k5rGM2zJF^^a7D-MR12F`T?7-Gk=*2#>=('
        '2*-%7W5|vIvHgnaQlbPG*F~jqw-OBxYhkF<X0%PyqyUK<3QxoQCgohJ&Y>Xq2cCVko`!SxwMxoTKZFd&2Z%VW#N=4!zhfBl8@?>5'
        '=^x6TCS6*35kJP2cJ|3K{3_LhvSNF}GbFE)Dy=;lI3P4;NTW5Hvge5C)l@Yft_|EC)qujw12kb7xb|J}`0t{lmx642)*pUsnP>SI'
        'Am7*lg9QKp'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
