# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/runner/work/packaged-dsdl-py/packaged-dsdl-py/submodules/public_regulated_data_types/reg/udral/physics/kinematics/geodetic/PointVar.0.1.dsdl
#
# Generated at:  2025-11-24 13:46:54.898071 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     reg.udral.physics.kinematics.geodetic.PointVar
# Version:       0.1
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import reg.udral.physics.kinematics.geodetic

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class PointVar_0_1:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 value:          None | reg.udral.physics.kinematics.geodetic.Point_0_1 = None,
                 covariance_urt: None | _NDArray_[_np_.float16] | list[float] = None) -> None:
        """
        reg.udral.physics.kinematics.geodetic.PointVar.0.1
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param value:          reg.udral.physics.kinematics.geodetic.Point.0.1 value
        :param covariance_urt: saturated float16[6] covariance_urt
        """
        self._value:          reg.udral.physics.kinematics.geodetic.Point_0_1
        self._covariance_urt: _NDArray_[_np_.float16]

        if value is None:
            self.value = reg.udral.physics.kinematics.geodetic.Point_0_1()
        elif isinstance(value, reg.udral.physics.kinematics.geodetic.Point_0_1):
            self.value = value
        else:
            raise ValueError(f'value: expected reg.udral.physics.kinematics.geodetic.Point_0_1 '
                             f'got {type(value).__name__}')

        if covariance_urt is None:
            self.covariance_urt = _np_.zeros(6, _np_.float16)
        else:
            if isinstance(covariance_urt, _np_.ndarray) and covariance_urt.dtype == _np_.float16 and covariance_urt.ndim == 1 and covariance_urt.size == 6:  # type: ignore
                # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                self._covariance_urt = covariance_urt
            else:
                # Last resort, slow construction of a new array. New memory may be allocated.
                covariance_urt = _np_.array(covariance_urt, _np_.float16).flatten()
                if not covariance_urt.size == 6:  # Length cannot be checked before casting and flattening
                    raise ValueError(f'covariance_urt: invalid array length: not {covariance_urt.size} == 6')
                self._covariance_urt = covariance_urt
            assert isinstance(self._covariance_urt, _np_.ndarray)
            assert self._covariance_urt.dtype == _np_.float16  # type: ignore
            assert self._covariance_urt.ndim == 1
            assert len(self._covariance_urt) == 6

    @property
    def value(self) -> reg.udral.physics.kinematics.geodetic.Point_0_1:
        """
        reg.udral.physics.kinematics.geodetic.Point.0.1 value
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._value

    @value.setter
    def value(self, x: reg.udral.physics.kinematics.geodetic.Point_0_1) -> None:
        if isinstance(x, reg.udral.physics.kinematics.geodetic.Point_0_1):
            self._value = x
        else:
            raise ValueError(f'value: expected reg.udral.physics.kinematics.geodetic.Point_0_1 got {type(x).__name__}')

    @property
    def covariance_urt(self) -> _NDArray_[_np_.float16]:
        """
        saturated float16[6] covariance_urt
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._covariance_urt

    @covariance_urt.setter
    def covariance_urt(self, x: _NDArray_[_np_.float16] | list[float]) -> None:
        if isinstance(x, _np_.ndarray) and x.dtype == _np_.float16 and x.ndim == 1 and x.size == 6:  # type: ignore
            # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
            self._covariance_urt = x
        else:
            # Last resort, slow construction of a new array. New memory may be allocated.
            x = _np_.array(x, _np_.float16).flatten()
            if not x.size == 6:  # Length cannot be checked before casting and flattening
                raise ValueError(f'covariance_urt: invalid array length: not {x.size} == 6')
            self._covariance_urt = x
        assert isinstance(self._covariance_urt, _np_.ndarray)
        assert self._covariance_urt.dtype == _np_.float16  # type: ignore
        assert self._covariance_urt.ndim == 1
        assert len(self._covariance_urt) == 6

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.value._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        assert len(self.covariance_urt) == 6, 'self.covariance_urt: saturated float16[6]'
        _ser_.add_aligned_array_of_standard_bit_length_primitives(self.covariance_urt)
        _ser_.pad_to_alignment(8)
        assert 288 <= (_ser_.current_bit_length - _base_offset_) <= 288, \
            'Bad serialization of reg.udral.physics.kinematics.geodetic.PointVar.0.1'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> PointVar_0_1:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "value"
        _des_.pad_to_alignment(8)
        _f0_ = reg.udral.physics.kinematics.geodetic.Point_0_1._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f1_ holds the value of "covariance_urt"
        _f1_ = _des_.fetch_aligned_array_of_standard_bit_length_primitives(_np_.float16, 6)
        assert len(_f1_) == 6, 'saturated float16[6]'
        self = PointVar_0_1(
            value=_f0_,
            covariance_urt=_f1_)
        _des_.pad_to_alignment(8)
        assert 288 <= (_des_.consumed_bit_length - _base_offset_) <= 288, \
            'Bad deserialization of reg.udral.physics.kinematics.geodetic.PointVar.0.1'
        assert isinstance(self, PointVar_0_1)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'value=%s' % self.value,
            'covariance_urt=%s' % _np_.array2string(self.covariance_urt, separator=',', edgeitems=10, threshold=100, max_line_width=1000000),
        ])
        return f'reg.udral.physics.kinematics.geodetic.PointVar.0.1({_o_0_})'

    _EXTENT_BYTES_ = 36

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.StructureType = _restore_constant_(
        'ABzY8&S4~J0{`vWU2ogg83%BRvSeD8ZCP;~HFjJkbra=HNxE)LySH?0Qx~i=FX@Ycq9ZBk#D@+=swCyw#fmZQI-~=E5hw@rBjh9W'
        'QoHL%=;bgBXtv#KcL8?MokRYQ?6Pst76Z1Sc91-eMC$PHh`)!&hY832aQCc~{zQ-Vce;MpZs|VpEYr5$G21q2=^eM%cYP}$Ni=mM'
        '@CKb=;E`8$`Xu=%Iej~MH)%#C-7$M?d&?smtwGl_?N*=e_*Tbn-Lf3gGXtJ(5VuQM)>?BdCwR^Dl1S0Fi050blTaxde+~IZi6&`<'
        '-zK+{Xi_(Wz_Z$efcVLq>`?o3a<o?xm9ARE?(TN3qIb=})C1mQDraxfQgrqk^fjU5bVBrrR#`u24GkUIuSb2)>RExc#d<Vx)ppI`'
        '%R@G)x2-_8iL(*VM7zRz*)jb<@3F%sbTOJ=6CdXvYdy!dt@2HLXg)};C()el2d2|Cz3$$I?yz=x=7wVhgDyYtP0#EEY)E}J)K`(S'
        'Hhy<o`fvT*|04ZK$MSkIXtQrZvDuhs9UjxWZin^t4bSXart>D>VKmZo3E6S&3Ozwj(o=V6lb-$GI++REbvClIp%?Z$k=?6M9hh4k'
        '(`oruYrwv>R`xx%UbnjBM#r?7k@V6lXp*?}{?Epv)FT1$_*h8n4Kq5l2ejVa$qL8234M`1>oXKx()UQm3`jTmFq+nHTHB<n_gyd0'
        't!{EHn$>-G;B^SwU=zJ>vP(W1=fSqx>~ddYb!vN!zxxp*R=B_}DC+XURQ3jr!@3cTz3qCplBm`<JGaaY(ml`Vp6~A@^wp^158BM%'
        'z-FZ;TIdhjw$;&Dl^EE(Kf6_gZ7pYCTN25>#Tw;b9eWc9qeHu2U+YrqVv8Rm3AoxrIyHUPZ;v<uuNPZZha?};3v?x_r9+WbTZe7V'
        '%H6{cRM~T#kmyJ{AbQ~Hp6do_b3Qvyb|J1c=`ZMYdV{_~UuAz@qp#ETv_E5d+h(V8Qk1aWQo?!{<X<OI^=DS_a{BrPdx>He6?M0t'
        'MCyKx_&dF}%f^zO{wnFYtU&TI^z%OP%)s?_OJZ5?P>WS=`c^cvW_G)lv+<Rk=oa64ZD6xg-pOxeEo_<gfF!?9n%b4vZ?pSLKWiw_'
        'ltG)FZqIUfwPlI9&69CG{l-n+wpQSulVVLqEb>^0wK2Rd@i-Q1WyEo8SFn8ouPfL-$>T(<Rq=X?$7-xi^Qgqy4BoHd^Rqlo#af-m'
        'N~|5?aXi-Mu-{>{KhNV_tR3O89%~IAYq9nSkJGVs6vtUWJBv8pF&@jYwuJT`<x!3`6~{l$<D;>5g2$y;dyL0pv9`?PVyr#R<3g;R'
        '<nd^%o#OG4SZngwh_%x^9*MOxJkH13Sso9^+Bx+1JdcNBt%ZJH;BhwAE~5XJc$|r~CvYC$!+1Q2^Z7oHld<*#oYzwr-^)0^r!ij7'
        ';5>iGV=2~tg!BC|kHuK~3C{bc7|$y>|CQ{z(bf?u;x^(P#E%j0B7TDSDdJ~{_Ym)AaaAcGX^5mLlFK4l5y`qps7SU&az`W|i{!3I'
        'J`u^MBKb@t_e63Z$$(83$add!(n%NIYy0i&rfk~5=r$HSZ}Hhihp255yiJIs29&6_%PNoBBc`MJ#8hpvMQpXXdgJBODw~<4yWC87'
        '>GL_1>fTJ>GM#`pj@eRqvE~yTRUAn*+b(;_cVdmS*zJPQm$>;BJxZUVm*`*U(*vq~NMF82S07N*q9QBSZ2p%{>iB&jo7S;1xjV6A'
        'a|<!GOQPv?a>okvrQH%ubykj}KfZ{a)O700#^)JT%u>#&qg(vB^h8DfTa{N>*IlnmJk|2m4t0G#Qm)Dl-J#jZZ?g^Q9;_yb5xMrl'
        '^D3LD_0WKCy+hJ=ZF9#RVBFZpd@=Xtjgz+qY+za2yn*LTkKIk#G=uk+4IrN}Ce+~fk8e68rEI=S=*EL?8lR^lv`Kquxut#TkE-(a'
        'DD(GJ>ch{u4!@f_4=nl7L{{<H-H_kx9^TrfT#%&n#b$|R`|ba$tZTm(w*Y!uE3gatJvK#ppZ)#KL7hLS^WU{PPyZ~6`&W1npW6tT'
        'jqo8h<eZHnY{;-7=WNKZp}@vCY$&iX2^%tOC^;Jwupz_7G;AoaA;U%;Hl|=hfsG<;G+<*6Hfpd@g$)HZ#&R}}!NyV8I074UurUi8'
        ')37lK8wzZcU_*wDGqBNwjgzpk3>zn4Lxqhc*jR*(qp;C{jd|FZgN-_D)L>&8Hma~ufei&V%CIp88*<LZW!PxKMguk!*a%@GgpCk3'
        'Lf8mlBZQ3*HbP+|6gEO(BNR45VIveaLSZ8mHbP+|6gEO(BNR45VIveaLSZ8mHbP+|<Th^e-w_Tp9B4Suz#IhGtzpP83?G6)%3+X!'
        'K>~(i4nq+bWMC)(g9Ho}V5k5?HHV=D3{_x|fuRZvMPR4_g8~c^Fw6o&1sICJ&;W)yFjRq|oWrmH4D-M+3k+3Y7zYL!7?y!S1%^dn'
        'XaK_;Fw}sd3JeM`i~)lL4CjI23^1GmhGk$l4h&1cumB7VU^om6bzqnQhAJ>j07DrVia87yfuRNr>%g!A43~kS2@DNjP=H|w3`1ZT'
        '0>e;X7zzwSfng{x3<ZXvz%UdTh62M-U>FJvLxEu^FboBTp};T{7={AFP+%DDy)_(YIMDE&*MJqGQnuF07q9m|+=v$Tc|zxT=1vmL'
        'UFA#q*&6b*{H-rP7Ms$EO?rHFJbPZZ`-r2q=Ml&1pS}=}82B23**7~@u#;%z2d_=M71ghkJ_)P`uRF{7E&kCjuN~Cl^fceo3`XAg'
        '2ILDl@}(U4GRT)fUdfR!fqWI@%Q^CsAYTUg0?5}uz6$aR$dBd79|rk4$j^X$733#Cz6|ok9Qh@XUj+H1Am0G_d61t2`8vqgKz<tJ'
        's~}$ic?IOlAU_83a*q53kZ*zfd5}K`@@GN*49K4b`6kGp0{N35|2W7mgZyJ4e*)x>gS-mz4Uktr-T-+6<PDHFK;8g(1LO^mH$dJ1'
        'c|(vl1bIV{Hw1Y@kT(Q*Ly$KFc|(vl1bIV{Hw1Y@kT(Q*Ly$KFc|(vlcF9k7+%1!#b~;2KcmcD&K2wmSH_~T(zkK4&%By{*>%3=e'
        '&_E6NjvF=+%bdHP<qM*owVf?@iUroa+bv)1lAD%8x~fO`x+`B6c2!diSc|MUSbS00HXXiL?74%DY;o1^la6)MBHhta?S;`wZL9J^'
        'R#!%=ulp_Nip5;@rQlnx;*J)sH~%3^5}n<oMM>KHC(9qUdQCs4_vl~g-{{|?S@9nv9<Ve`SH9iCt}^;h7yps9-LJVC`>)aR>%q+F'
        'VCM9lpE+$xtP-TZSFfrC`ab{X>x(GnMC2bxNV#PuIVVESJ&-8oMARTcf{0>nnP~<hWQeHdL`*@13=#F*1BnHQs6)g=PDBGDY7n77'
        'gai@CAYvXOW^&6+1&CONh$V<<KtvrPst{4mi8u=pCn4fEL@YwY5s0Wm#8mEqL=hq`L&TF1aS<ZUK|~WGmU9ye2_hO0u?7(rA)*Em'
        'cOYULA}B<xL&OS1T!x6I5YZ4K6o_EgA4sIx$|zeOWptEnkFq<X?Bh{(ca(iH%03-spN+D6qwK!OG9PI+`bGPI#{rK69$(?Xr{S%C'
        '0}^L~oU<zc00'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
