# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/runner/work/packaged-dsdl-py/packaged-dsdl-py/submodules/zubax_dsdl/zubax/low_level_io/Data.1.0.dsdl
#
# Generated at:  2025-09-11 16:13:22.705876 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     zubax.low_level_io.Data
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import uavcan.primitive.array

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class Data_1_0:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self, *,
                 u8:  None | uavcan.primitive.array.Natural8_1_0 = None,
                 u16: None | uavcan.primitive.array.Natural16_1_0 = None,
                 u32: None | uavcan.primitive.array.Natural32_1_0 = None,
                 u64: None | uavcan.primitive.array.Natural64_1_0 = None) -> None:
        """
        zubax.low_level_io.Data.1.0
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        If no parameters are provided, the first field will be default-initialized and selected.
        If one parameter is provided, it will be used to initialize and select the field under the same name.
        If more than one parameter is provided, a ValueError will be raised.
        :param u8:  uavcan.primitive.array.Natural8.1.0 u8
        :param u16: uavcan.primitive.array.Natural16.1.0 u16
        :param u32: uavcan.primitive.array.Natural32.1.0 u32
        :param u64: uavcan.primitive.array.Natural64.1.0 u64
        """
        self._u8:  None | uavcan.primitive.array.Natural8_1_0 = None
        self._u16: None | uavcan.primitive.array.Natural16_1_0 = None
        self._u32: None | uavcan.primitive.array.Natural32_1_0 = None
        self._u64: None | uavcan.primitive.array.Natural64_1_0 = None
        _init_cnt_: int = 0

        if u8 is not None:
            _init_cnt_ += 1
            self.u8 = u8  # type: ignore

        if u16 is not None:
            _init_cnt_ += 1
            self.u16 = u16  # type: ignore

        if u32 is not None:
            _init_cnt_ += 1
            self.u32 = u32  # type: ignore

        if u64 is not None:
            _init_cnt_ += 1
            self.u64 = u64  # type: ignore

        if _init_cnt_ == 0:
            self.u8 = uavcan.primitive.array.Natural8_1_0()  # Default initialization
        elif _init_cnt_ == 1:
            pass  # A value is already assigned, nothing to do
        else:
            raise ValueError(f'Union cannot hold values of more than one field')

    @property
    def u8(self) -> None | uavcan.primitive.array.Natural8_1_0:
        """
        uavcan.primitive.array.Natural8.1.0 u8
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._u8

    @u8.setter
    def u8(self, x: uavcan.primitive.array.Natural8_1_0) -> None:
        if isinstance(x, uavcan.primitive.array.Natural8_1_0):
            self._u8 = x
        else:
            raise ValueError(f'u8: expected uavcan.primitive.array.Natural8_1_0 got {type(x).__name__}')
        self._u16 = None
        self._u32 = None
        self._u64 = None

    @property
    def u16(self) -> None | uavcan.primitive.array.Natural16_1_0:
        """
        uavcan.primitive.array.Natural16.1.0 u16
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._u16

    @u16.setter
    def u16(self, x: uavcan.primitive.array.Natural16_1_0) -> None:
        if isinstance(x, uavcan.primitive.array.Natural16_1_0):
            self._u16 = x
        else:
            raise ValueError(f'u16: expected uavcan.primitive.array.Natural16_1_0 got {type(x).__name__}')
        self._u8 = None
        self._u32 = None
        self._u64 = None

    @property
    def u32(self) -> None | uavcan.primitive.array.Natural32_1_0:
        """
        uavcan.primitive.array.Natural32.1.0 u32
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._u32

    @u32.setter
    def u32(self, x: uavcan.primitive.array.Natural32_1_0) -> None:
        if isinstance(x, uavcan.primitive.array.Natural32_1_0):
            self._u32 = x
        else:
            raise ValueError(f'u32: expected uavcan.primitive.array.Natural32_1_0 got {type(x).__name__}')
        self._u8 = None
        self._u16 = None
        self._u64 = None

    @property
    def u64(self) -> None | uavcan.primitive.array.Natural64_1_0:
        """
        uavcan.primitive.array.Natural64.1.0 u64
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._u64

    @u64.setter
    def u64(self, x: uavcan.primitive.array.Natural64_1_0) -> None:
        if isinstance(x, uavcan.primitive.array.Natural64_1_0):
            self._u64 = x
        else:
            raise ValueError(f'u64: expected uavcan.primitive.array.Natural64_1_0 got {type(x).__name__}')
        self._u8 = None
        self._u16 = None
        self._u32 = None

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        if self.u8 is not None:  # Union tag 0
            _ser_.add_aligned_u8(0)
            _ser_.pad_to_alignment(8)
            self.u8._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        elif self.u16 is not None:  # Union tag 1
            _ser_.add_aligned_u8(1)
            _ser_.pad_to_alignment(8)
            self.u16._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        elif self.u32 is not None:  # Union tag 2
            _ser_.add_aligned_u8(2)
            _ser_.pad_to_alignment(8)
            self.u32._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        elif self.u64 is not None:  # Union tag 3
            _ser_.add_aligned_u8(3)
            _ser_.pad_to_alignment(8)
            self.u64._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        else:
            raise RuntimeError('Malformed union zubax.low_level_io.Data.1.0')
        _ser_.pad_to_alignment(8)
        assert 16 <= (_ser_.current_bit_length - _base_offset_) <= 2072, \
            'Bad serialization of zubax.low_level_io.Data.1.0'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> Data_1_0:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        _tag0_ = _des_.fetch_aligned_u8()
        if _tag0_ == 0:
            _des_.pad_to_alignment(8)
            _uni0_ = uavcan.primitive.array.Natural8_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = Data_1_0(u8=_uni0_)
        elif _tag0_ == 1:
            _des_.pad_to_alignment(8)
            _uni1_ = uavcan.primitive.array.Natural16_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = Data_1_0(u16=_uni1_)
        elif _tag0_ == 2:
            _des_.pad_to_alignment(8)
            _uni2_ = uavcan.primitive.array.Natural32_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = Data_1_0(u32=_uni2_)
        elif _tag0_ == 3:
            _des_.pad_to_alignment(8)
            _uni3_ = uavcan.primitive.array.Natural64_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = Data_1_0(u64=_uni3_)
        else:
            raise _des_.FormatError(f'zubax.low_level_io.Data.1.0: Union tag value {_tag0_} is invalid')
        _des_.pad_to_alignment(8)
        assert 16 <= (_des_.consumed_bit_length - _base_offset_) <= 2072, \
            'Bad deserialization of zubax.low_level_io.Data.1.0'
        assert isinstance(self, Data_1_0)
        return self

    def __repr__(self) -> str:
        _o_0_ = '(MALFORMED UNION)'
        if self.u8 is not None:
            _o_0_ = 'u8=%s' % self.u8
        if self.u16 is not None:
            _o_0_ = 'u16=%s' % self.u16
        if self.u32 is not None:
            _o_0_ = 'u32=%s' % self.u32
        if self.u64 is not None:
            _o_0_ = 'u64=%s' % self.u64
        return f'zubax.low_level_io.Data.1.0({_o_0_})'

    _EXTENT_BYTES_ = 259

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.UnionType = _restore_constant_(
        'ABzY8BK5*(0{`uuO>7(25rDb>EC14VY%8%-GqK~)jxEc-QQ|mJlb}^Q9anIgz-<w%R?@~xg(3<5IC6lX%%KGXEYL->1#}6ZqmBl8'
        '@sYi>x>ZN@rv9K6&_DGLaC_>TT`u>L67^$Ib{%g5NaVivX6DU%OTU?KR;<cDoxh#%|8tHN?u?hlvwcR%DrU@V=3{d-YxNmp`N=}Q'
        'lqp-D)AMdFlh1wUPQmg%_fCE4ed47Z#mJeHtnKi}l~Hr5FPs0!$Xd6ptdYt0y=|6F&(V$BR<XnedUnFm-fO)6+yem;Kk`2HoSlYQ'
        'E*CSSm9kax-e)p9Skmm}Im*{ER(3qHVuvx#bQxtbjcM8aPPteaD_4qEi?O!i9IKeO$IM(`p_rM>lry)jKC@Uf@AO?aS#L8t;Mtnp'
        '6Iy2Pdf&5?jj;!uBOS~l0n7pKnd~aN@+~WOt89OjuC}^rw_#<iNh?<l?CdnnrfHsY;N4s)b1P?!e<N46Zdt`vc{`2KOqqF`)OnyY'
        'Cybe;vN4$-XHGcb92yP<(XhU^SQ}Ck^L*lm-VM)r$|#l1+_+gB=LOX&qfQT#R4~Uf<vSiG1ZRJv&G>-4-th9thF?xW(mrjU0fA)N'
        '=V-WWjAl!ob26M?B%MvQ-2UEkcD<P?2VQ%Jy=~0Tk&Jx7b5fmzl<rK9=CheG<|VWy^UQl?wy(Zju!?3mUyQt@8e?{b?G^i)bMUQv'
        'Zp<uOxmCN;tf^<w%F!-l{r6t4WV2@R&WfI@aofyREbqr&8j@~l)PAGkj5pb+!#B*_E$fC=u*#WECVgm3np5OkHsYK9RU1i|&V>06'
        'oXq6dGSLgapYCY1u9d7w0zja?2^Yl1Z^{47wyo%b+_<JRuYm-z3u^FQq}N(Y8z`W<pf|?#tY`y`*#$eA<JlGVe&?$Fpa*uiuq$ZO'
        'N!RX<{a`2Ta$!%4Ty~XR+q>o%*bRGJNH%o1uy5Vou$L_p>|ddYwXo|4HZ&gg!G0H>3i`^deHV>AxZ$yI0G@K;(5g1DR@QcSQ?lS7'
        '9CD#I^fa^O=}nJ^!_e!(GaYSWJy`pZ2a*d<!!s@%ZSfatW%8bVV0mx^j=J!bHSJ}+Sf68C(gDxHS6oOneM?q9w`GZN3{oyUAIM3q'
        'Wj|>@-W7fD96ayBiBKoE4&<d5x~2n;!wDBouDdd9M2huheP8UVZg>Gsx{wa%*;unvUDp9GLfVDX8=fZ{!TP_nEq1^uIPJojXl+k0'
        'nQ4A~&u*JucnQw9(6=c+uu*Kxxox!x&O)CH{n0*12Rq^XwrhoR(C@;9O?!lmWaBPA6#L*jTyWvi${llt$?gw#&E<z?3tWUtE?jva'
        'pRv(w?8^_;R=5mTTo`EGUH!DbUU}$tz{@b;!mAJLJ0^jRzxqh*hF9QK7hdbU4=*tt1GE>fJu>^?D!k^x>s#_Klfq=Y@kr+Y*Wh&*'
        '23PD^w)zzoGFnpwGv`O-eh*BDn2<4{vX}#O)J4=~ysx0HLK2fACS^>j(2Kny_R83+;(ZNLm=ZB1V@icIrbSH4m{y@5`$g=Rv0sG&'
        '91w9p#sL)uaZtoT83$Du!XXidWE@gq7>7k1mT_2xn|M>in=;;1VFX7+9FcKE1siP<Z5eG93Rn=aAY(y=DV!2<O2#P_s#q1VDq~fJ'
        '8rDRt$yigtMOQ>uMpuPtoEC9f#%UF1a7M%#8D~_O#aR(&Wt>&vF5VUKu8en8xQF*dyeH#573x?Qu`Xj>g*luPaZbiL73OhX#CaL#'
        'Ran3U5f@}!P+<`lMO>6|QH3R35^+h!B^8!&S;S=-msPlr_eH$V{K>p4U_!!#f(Z?E0d)y==41_%0wyI)Dwx!;SHNBgdll@}FePA0'
        '!jyt34buXqB}^-r*05i|ehK>(?ALHWzyS#d6dcfSP{2V62NfLDa7e%*35OIM(r{S7VF`y79M<rrfHx()so+fwM+6*^a74io4Q&B!'
        '32g;!4GRJmBrGUc&~Qq?DG8?(oYJr=U{%7Zf>jM`0@fs~DOl6c70{K?RnXONTEJ-urxl#ma7Mrx31<|X(QsD4SqWzqoYnBIfOjRl'
        'tKeM??+JKM!g~td)37dJUBbG8bq(hPoRe@)!8r}*1)P^~Ucq?{7X)08@V<l#3NC24DBz-miwZ7kxFq0`gi8u8X}B!lvV_YDE^ByS'
        'a4Vx03)sI4N&9=4)a~y-Hu1Dhaa0^nKZJNX8TcWNr?(-VW~cGMyIqZ^Q|tX3y$$hns&yT{wDEK*%7HvF@ifi(1e2U@UEe1<o+h89'
        '!<`Vv({1r|>yC-z>CMK|!KX}`wI$<tdJFM%@UK!FPd|)!I{HLx#MAZ{>@puhv$z>`J&d8nMhva8z=I-b3ZngBT7HyaGz*_u98JNr'
        'ym}Z-;d3LBj>G6LYZx8G&@7nVa2QRb+EyGTK;e#TjOWKZC*f5_P3Hht(qW9=32H<>@$BE&M@!C5W85kfEh6#b-e=Ap<AcnUHEtC0'
        '#j=qZ_pUqpj8eW*9J5$M)-noa+4dZbeq}SGp3^g&FJ-2N>FVcR+7Zq%-FBX8P}E{2m$QoO{YUxYhn|xxm}4KBx2*BAR6=mJaL2Qk'
        'ogJmhsE^XElII*LR7SIzF{5bRs$|KYsE&lSszI>`Q_0n2D2;lLePPK+-}%1&K2qS7sjA|DVVfmpbdd@@N>=f9X3X+Fvwv&<&Pn=y'
        '2r6oFtU0K5SyPMNEKISS!@etwa^5KB^JQOFiOtaR>_4ULKihw?|7!ouUS|LQ-TsIDPcp{7V!skp7rfR|qOf<^93Ri*ZmlRyV6B6W'
        '&h+@r9_W?UREhn?_2$Bhl>v{Y#ojb)WbA{@N}JT$l{V+EtWj!Xry8%0x0RXn`2{9+KUD4WT$9e4E(cAk&iL)%($}f1qrKdM>vp5@'
        '>Rl$jwJsy+*JUtQB$z7_k5ks@p;TeSIU_bE8Rv|)tp+0**I&f-7jgZ?V^)8Wr28$-6vdSnapgr^dGUl-Ua-$X_GuGjh}z05xWWo9'
        '2gD_QxNHxX;^Fc-TulU*!QrYOxLggFpy9GITq=gkzeGuwmP`wuUEwn-d=`bzobcHaK10H1MfgkzpZ(x79(<OA&usA73_g9qr7W7*'
        'UuOZF9%KL304|39fuG|d`t1qe^sX1s$G|@Z{@Vfk;{YxS;MiSDzK;XA4yZp4;9}Gtqy8r&fb%~Kn~1+r8PBo(R+P{2`vITWiv;aC'
        'QqSS}h{^LHo-1PKkUPiOIk?Udbq=FP>^xxQ0XF9$IS<Cu91rIKI1jyf(9Oeb9%%Crn+MlCtmXkV52f2cG!LIw0nPz>H0|Gi;!XTa'
        'NF*i>u^%P-51-k8ylyY8ibU;y+5dL-HvwcTxV8V|Lt6X4>oVD%2w_?i38r;({B=TSLz-_=Wcp6_qrqCE_>^a@QiXWw1H;yf7d8u9'
        'Q#@=P++Nr^*alluF>H-tYy80bqk^q5YK>8Aj9O#V8l%=2wZ^D5My-$EL+(w?3RU8kRe^A8RV08}m594mWg?J^3XZ6_sN#smG|v#q'
        'oDm4X&WOY`XCxxAGcrNXMUBv8LdB{|0JN&XAk>L*)&*j-b&+6aT_Q+Zmx+cZbYhk%6=zf;qca+ez#_rVMS-yGqDT~UQ6hf3C=({F'
        'D>$fPT_s*xk8x#;E7!%9Nm{o!1lkT<8N<pLR>rV0hLtg_jA3OAD`Qys*ulzl_$+c-!&!}RrGPa7YJ@FoA|b$<MC7t26F3}Fh`=og'
        'IHVGcoKp!M4rxUA<}_x(EV02^fuQEBNRV(=BDy&%6SrKFVF>036wV0*IOjwnhI0~;PF*2{SED~4M$ZxJ8ezdDm7t-m5Zbd<qI<dy'
        'HY^cSOe@3)(<;uYYXZNlm`F_gYIDHv;)SgOzl#^T0Q`QvLEuNs?ty{dl}noieuF&lOKmUkOSJ*N!5H|(z%PEf@(Bihk+yEbK7KYU'
        '=dx0IHzM5D8IjJt{-~AndDb7lQLq=zC6pV^<bZEaAT{(+D0Qn*?0P$4<Irxczo!-MI-T=as3V$LsOR~nj#FEXOoJU5%rej&`Sf6m'
        'PlNddnuAkWCjdt>qjd^=MzcBSTl2JUPq;=TFYr}x#@mkQvVGOs@1zwG^(B7I!V`Ocv~HLAJ=wl$(OnhV8Scc!dPPxP7a~Ib{^sWy'
        '-DA<djOMs8&=txKcYe6%!%vG)a_GPCe7+q~TVM&lLxazfz?NVogL|*JH~m@qc5DJd(as6(#GdA7%s$`ZgN-$fKD9{Si@vUYrs)cc'
        'ME<WLsSpTpPu&Uhe4NmD`i`EGYeFGqO~6B3CuBTzndnZ8Y+_^+KVcRln>F;Ub<Es2u30IapUdh;%B>w@g$_Dfy%+vt(0=?|56!GT'
        'mz9UTqfM#dk+ORzX1$&8px8xT5o#nke}(d+d4)PoZ|M*#G!LA5OJERa=8v$vKZ9dJXN1yzFpgF!@E6S{3N)f)ad!`~EAQX-)oKqp'
        'I^&Ns{;IX&55Yg~M7yzl#ae@olg)!N&GCGfum-;~`Foq6X>@-@NA+eRcuiEXQg*oK!`&Vpk3-2}lDWHwSh6GVa$p6&JA==Vz>Z)Y'
        'gJXJN2OXz3gAoMQBiyyYJs5?^Vel2K=<(*RC4J|7T?25ni-*`Q;O8KvA13tu9C~X)Kgi?P#3+?Nq*4-pNTa7}{9J!)ihf9rvh=#b'
        '<>&P^lkP7_iNr)r+*H#2%B8I)-LG8gLel*w;>MEhlsEThY|)I<6T3<8zKLH@&VCR5_yGy}CA}ITZ&caaN=I)vJNz$2HT>B-ivPxQ'
        'cJbel>N&gVTT<6>Qiox(|K+M3JTvhs8F!Wa@c$&`UZZT@>hR^A>m>JE+_?Fi|21c~|DCbze`wMlIH8aqe@;I>CbwQ>_C_HT_Xj7V'
        'FYM@zF7nIS)<nzM_dj?ZGNs#g000'
    )
    assert isinstance(_MODEL_, _pydsdl_.UnionType)
