# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/runner/work/packaged-dsdl-py/packaged-dsdl-py/submodules/starcopter-dsdl/starcopter/temp/bms/AnalogDebug.0.2.dsdl
#
# Generated at:  2025-09-11 15:53:02.624672 UTC
# Is deprecated: yes
# Fixed port ID: None
# Full name:     starcopter.temp.bms.AnalogDebug
# Version:       0.2
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import warnings as _warnings_
import uavcan.si.unit.voltage

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class AnalogDebug_0_2:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 vi_raw:        None | uavcan.si.unit.voltage.Scalar_1_0 = None,
                 vbat:          None | uavcan.si.unit.voltage.Scalar_1_0 = None,
                 vrefint:       None | uavcan.si.unit.voltage.Scalar_1_0 = None,
                 vrefint_error: None | uavcan.si.unit.voltage.Scalar_1_0 = None,
                 key_voltage:   None | uavcan.si.unit.voltage.Scalar_1_0 = None,
                 pack_raw:      None | uavcan.si.unit.voltage.Scalar_1_0 = None,
                 vref:          None | uavcan.si.unit.voltage.Scalar_1_0 = None) -> None:
        """
        starcopter.temp.bms.AnalogDebug.0.2
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param vi_raw:        uavcan.si.unit.voltage.Scalar.1.0 vi_raw
        :param vbat:          uavcan.si.unit.voltage.Scalar.1.0 vbat
        :param vrefint:       uavcan.si.unit.voltage.Scalar.1.0 vrefint
        :param vrefint_error: uavcan.si.unit.voltage.Scalar.1.0 vrefint_error
        :param key_voltage:   uavcan.si.unit.voltage.Scalar.1.0 key_voltage
        :param pack_raw:      uavcan.si.unit.voltage.Scalar.1.0 pack_raw
        :param vref:          uavcan.si.unit.voltage.Scalar.1.0 vref
        """
        _warnings_.warn('Data type starcopter.temp.bms.AnalogDebug.0.2 is deprecated', DeprecationWarning)

        self._vi_raw:        uavcan.si.unit.voltage.Scalar_1_0
        self._vbat:          uavcan.si.unit.voltage.Scalar_1_0
        self._vrefint:       uavcan.si.unit.voltage.Scalar_1_0
        self._vrefint_error: uavcan.si.unit.voltage.Scalar_1_0
        self._key_voltage:   uavcan.si.unit.voltage.Scalar_1_0
        self._pack_raw:      uavcan.si.unit.voltage.Scalar_1_0
        self._vref:          uavcan.si.unit.voltage.Scalar_1_0

        if vi_raw is None:
            self.vi_raw = uavcan.si.unit.voltage.Scalar_1_0()
        elif isinstance(vi_raw, uavcan.si.unit.voltage.Scalar_1_0):
            self.vi_raw = vi_raw
        else:
            raise ValueError(f'vi_raw: expected uavcan.si.unit.voltage.Scalar_1_0 '
                             f'got {type(vi_raw).__name__}')

        if vbat is None:
            self.vbat = uavcan.si.unit.voltage.Scalar_1_0()
        elif isinstance(vbat, uavcan.si.unit.voltage.Scalar_1_0):
            self.vbat = vbat
        else:
            raise ValueError(f'vbat: expected uavcan.si.unit.voltage.Scalar_1_0 '
                             f'got {type(vbat).__name__}')

        if vrefint is None:
            self.vrefint = uavcan.si.unit.voltage.Scalar_1_0()
        elif isinstance(vrefint, uavcan.si.unit.voltage.Scalar_1_0):
            self.vrefint = vrefint
        else:
            raise ValueError(f'vrefint: expected uavcan.si.unit.voltage.Scalar_1_0 '
                             f'got {type(vrefint).__name__}')

        if vrefint_error is None:
            self.vrefint_error = uavcan.si.unit.voltage.Scalar_1_0()
        elif isinstance(vrefint_error, uavcan.si.unit.voltage.Scalar_1_0):
            self.vrefint_error = vrefint_error
        else:
            raise ValueError(f'vrefint_error: expected uavcan.si.unit.voltage.Scalar_1_0 '
                             f'got {type(vrefint_error).__name__}')

        if key_voltage is None:
            self.key_voltage = uavcan.si.unit.voltage.Scalar_1_0()
        elif isinstance(key_voltage, uavcan.si.unit.voltage.Scalar_1_0):
            self.key_voltage = key_voltage
        else:
            raise ValueError(f'key_voltage: expected uavcan.si.unit.voltage.Scalar_1_0 '
                             f'got {type(key_voltage).__name__}')

        if pack_raw is None:
            self.pack_raw = uavcan.si.unit.voltage.Scalar_1_0()
        elif isinstance(pack_raw, uavcan.si.unit.voltage.Scalar_1_0):
            self.pack_raw = pack_raw
        else:
            raise ValueError(f'pack_raw: expected uavcan.si.unit.voltage.Scalar_1_0 '
                             f'got {type(pack_raw).__name__}')

        if vref is None:
            self.vref = uavcan.si.unit.voltage.Scalar_1_0()
        elif isinstance(vref, uavcan.si.unit.voltage.Scalar_1_0):
            self.vref = vref
        else:
            raise ValueError(f'vref: expected uavcan.si.unit.voltage.Scalar_1_0 '
                             f'got {type(vref).__name__}')

    @property
    def vi_raw(self) -> uavcan.si.unit.voltage.Scalar_1_0:
        """
        uavcan.si.unit.voltage.Scalar.1.0 vi_raw
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._vi_raw

    @vi_raw.setter
    def vi_raw(self, x: uavcan.si.unit.voltage.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.voltage.Scalar_1_0):
            self._vi_raw = x
        else:
            raise ValueError(f'vi_raw: expected uavcan.si.unit.voltage.Scalar_1_0 got {type(x).__name__}')

    @property
    def vbat(self) -> uavcan.si.unit.voltage.Scalar_1_0:
        """
        uavcan.si.unit.voltage.Scalar.1.0 vbat
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._vbat

    @vbat.setter
    def vbat(self, x: uavcan.si.unit.voltage.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.voltage.Scalar_1_0):
            self._vbat = x
        else:
            raise ValueError(f'vbat: expected uavcan.si.unit.voltage.Scalar_1_0 got {type(x).__name__}')

    @property
    def vrefint(self) -> uavcan.si.unit.voltage.Scalar_1_0:
        """
        uavcan.si.unit.voltage.Scalar.1.0 vrefint
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._vrefint

    @vrefint.setter
    def vrefint(self, x: uavcan.si.unit.voltage.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.voltage.Scalar_1_0):
            self._vrefint = x
        else:
            raise ValueError(f'vrefint: expected uavcan.si.unit.voltage.Scalar_1_0 got {type(x).__name__}')

    @property
    def vrefint_error(self) -> uavcan.si.unit.voltage.Scalar_1_0:
        """
        uavcan.si.unit.voltage.Scalar.1.0 vrefint_error
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._vrefint_error

    @vrefint_error.setter
    def vrefint_error(self, x: uavcan.si.unit.voltage.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.voltage.Scalar_1_0):
            self._vrefint_error = x
        else:
            raise ValueError(f'vrefint_error: expected uavcan.si.unit.voltage.Scalar_1_0 got {type(x).__name__}')

    @property
    def key_voltage(self) -> uavcan.si.unit.voltage.Scalar_1_0:
        """
        uavcan.si.unit.voltage.Scalar.1.0 key_voltage
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._key_voltage

    @key_voltage.setter
    def key_voltage(self, x: uavcan.si.unit.voltage.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.voltage.Scalar_1_0):
            self._key_voltage = x
        else:
            raise ValueError(f'key_voltage: expected uavcan.si.unit.voltage.Scalar_1_0 got {type(x).__name__}')

    @property
    def pack_raw(self) -> uavcan.si.unit.voltage.Scalar_1_0:
        """
        uavcan.si.unit.voltage.Scalar.1.0 pack_raw
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._pack_raw

    @pack_raw.setter
    def pack_raw(self, x: uavcan.si.unit.voltage.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.voltage.Scalar_1_0):
            self._pack_raw = x
        else:
            raise ValueError(f'pack_raw: expected uavcan.si.unit.voltage.Scalar_1_0 got {type(x).__name__}')

    @property
    def vref(self) -> uavcan.si.unit.voltage.Scalar_1_0:
        """
        uavcan.si.unit.voltage.Scalar.1.0 vref
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._vref

    @vref.setter
    def vref(self, x: uavcan.si.unit.voltage.Scalar_1_0) -> None:
        if isinstance(x, uavcan.si.unit.voltage.Scalar_1_0):
            self._vref = x
        else:
            raise ValueError(f'vref: expected uavcan.si.unit.voltage.Scalar_1_0 got {type(x).__name__}')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.vi_raw._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.vbat._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.vrefint._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.vrefint_error._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.key_voltage._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.pack_raw._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.vref._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        assert 224 <= (_ser_.current_bit_length - _base_offset_) <= 224, \
            'Bad serialization of starcopter.temp.bms.AnalogDebug.0.2'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> AnalogDebug_0_2:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "vi_raw"
        _des_.pad_to_alignment(8)
        _f0_ = uavcan.si.unit.voltage.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f1_ holds the value of "vbat"
        _des_.pad_to_alignment(8)
        _f1_ = uavcan.si.unit.voltage.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f2_ holds the value of "vrefint"
        _des_.pad_to_alignment(8)
        _f2_ = uavcan.si.unit.voltage.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f3_ holds the value of "vrefint_error"
        _des_.pad_to_alignment(8)
        _f3_ = uavcan.si.unit.voltage.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f4_ holds the value of "key_voltage"
        _des_.pad_to_alignment(8)
        _f4_ = uavcan.si.unit.voltage.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f5_ holds the value of "pack_raw"
        _des_.pad_to_alignment(8)
        _f5_ = uavcan.si.unit.voltage.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f6_ holds the value of "vref"
        _des_.pad_to_alignment(8)
        _f6_ = uavcan.si.unit.voltage.Scalar_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        self = AnalogDebug_0_2(
            vi_raw=_f0_,
            vbat=_f1_,
            vrefint=_f2_,
            vrefint_error=_f3_,
            key_voltage=_f4_,
            pack_raw=_f5_,
            vref=_f6_)
        _des_.pad_to_alignment(8)
        assert 224 <= (_des_.consumed_bit_length - _base_offset_) <= 224, \
            'Bad deserialization of starcopter.temp.bms.AnalogDebug.0.2'
        assert isinstance(self, AnalogDebug_0_2)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'vi_raw=%s' % self.vi_raw,
            'vbat=%s' % self.vbat,
            'vrefint=%s' % self.vrefint,
            'vrefint_error=%s' % self.vrefint_error,
            'key_voltage=%s' % self.key_voltage,
            'pack_raw=%s' % self.pack_raw,
            'vref=%s' % self.vref,
        ])
        return f'starcopter.temp.bms.AnalogDebug.0.2({_o_0_})'

    _EXTENT_BYTES_ = 60

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.DelimitedType = _restore_constant_(
        'ABzY8Uhu+b0{`8Y-ES2|6u|E-r7bOOLB2ukA__&|@{NFee+9C%Hh_pGxXkVj_blw)U3X_MtqBP{NQ#-nO&Aj%dE`HkM;>`Ih8Qu#'
        'h#>|{{CeaK&+I+huS?a$_+kn9ojr5r%*>fHbLL)c{o>1>QvN6Vq7gT7{fd?F*kiu;3A24(v7E3Lg^4G)lHG^7@6}LrPme@g-BfF?'
        'sVk~qwpm^f@K`}fcApY)>WDPvlTBt?0jr^lzC^It2_wPdir}@VV%L(&fq?m8^)R>7s*)X6oyUn62HIWw8Io@*vt+hhSJ#y6vX~ID'
        'XQzTE>Kyu>X5wR3O3pm$ao-)EO{e8D!7QPt2<;6ebjsx^t2->HBwi&AJW;8KzF<{eIpr{);qqofk6AWLdKNJEoPq_^bMbUjh+-Ws'
        'uZ~lgb<_`;m>iTY%l3rj^Pnm~nFdbFVTrJ6p^MX6Ar}r6-F3IhA#5AaO*$5zs*_62w=kN4%VKw;qfzuzV^v&0>gs_n#LN*G!vte{'
        'lw|br+1%2^zZWlFl+5yVbeq~3idMaLC0i{wbd)TilF4}!0&m$PjUBzBU<>pmxE7a3F?Sedhq@tqtP9>ScdaOlh2^<wP|mfIFpV9K'
        '4L-LbhBKAz8op=aEQc`1hKIEFCPt>b0mp_=XG~k1=E)^nFNg6ZCFexUxrDpouGbM?AB`wDC_9tX#;~P6ri5G;rMB-mR?MrZujezq'
        '+t}LH*kmPJ5)Yl~jmC-4Rx8=t*zC%t%EpQwKnWe`c^0q)Cmr)Z=sm7`4p%o|D{PZ<@;Ee(Nr26bocx<n+9;*CT$G2x5}_4`p~!tD'
        'xI#>TJ^ip3_Q8HQ00;5kAvg?2^2xMXwvP*0Rpi|G-s9B7)NdtcAN0hD{QDGsQufIiRv0O1Oy?vSso5b$5!XJzYawQ|&YO259y1Zf'
        '6VJW_9-b}uNcIjf*Y$#GlMy(&bujgD$s<!+(L<g2DOaDXe$&Vj8*hN9;YgVssg296d4WD2D6nBIv|IUJGws{#(EUo8Sthm+XK1!$'
        'W-EQqr0+IjyJl-<&eEKjnVqEX((KI4*_s`h*{#`@nLT9ROLlX}?_AB^%zQ<&Co|`1c4y{%&Doi`K(i||7n0vanzJ%<G5KGj*`Aq8'
        'X`E#=pI2$T<(e}x^EDc`PqUnv293X>5jXR7;!5Hh#5aknh^vYH#5KgXh--=Ki0g?J;s)YI;wIu|;uhjo;x^)T;@iX>#GS-l#CM3h'
        'iF=59iTjBAiN}a%i9j4CjuLMX?-1`2?-L&qpAnxoIM7ihVR0e!7s8H0I93Q}3jqpYxDZAQ;Z`BsDTKR)aK8{97Q(Yacuqo!w>uw>'
        'Sdf=R(%Fff-`Z_;&x+Y)1zY7Jq~WBozOjrNX9<?%8p`^5AFEriB){ryCUlntWab)Y4jwpd6qi*~hxU5RFL*)TXXRKQRPY!Jxq*!w'
        'M|Jr09=gec#p4)n0`#-n^)3|MY%VTy9vFB<dUmWYa09EHF*eda7@+GCAF+y7Jxv{rF$dIOFkuMbhI!-zBf=}D$xDYWHAO&|PI7T('
        '=)fU!`te)!0(GyAXHFhDy0$P}XYfRLwR}l+j~Tl0_~7X&`@><o_VhI@gm2&hd<Wmc_wWdQgdgB1cmhAe(-d}$!p=e1)l?*8@Av~N'
        'FOUjr<Cq3(hkkV7<&V!Ud_PQhcwxEQJYMkNL|)urK-aSA9du26xp6q%T(f?GUvq!&!-si*;2fMED++u}IzORMEI1Sf`WX?twBpEF'
        'je>&-pbPC^d%HNJTq@-s7u!(!zuGehbftvQG$6wNA7h-q8bk%-iPr8%?f!9XVLU}m#^+IczS($+nvAca_G+{76g3&&M(yop<0)z~'
        'zK7a-&BjyIWc(PlkDHArs~dMDbm238j()!P<N11kXX_E3t0(aE-<&#~=I|T*4uAX?hX>y~d|2qaVc>CDF2sj+<5yU00cS3v@jGUP'
        'ocA79g=)av<9HWWc|7UY2CTx&SPg5;vi|J=>qapeFFTbl$vLlK<QFfrNyl~3NfuQ3Ngi?GP4`5+)Ofk=#tsvGb!7RTgk}jMT$<jg'
        ';yIV(Th`cJOzMGBOLMF4T=^3;N<=}z4gdf'
    )
    assert isinstance(_MODEL_, _pydsdl_.DelimitedType)
