# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/runner/work/packaged-dsdl-py/packaged-dsdl-py/submodules/zubax_dsdl/zubax/physics/kinematics/cartesian/Point.0.1.dsdl
#
# Generated at:  2025-09-12 07:48:17.127669 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     zubax.physics.kinematics.cartesian.Point
# Version:       0.1
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import uavcan.si.unit.length

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class Point_0_1:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 value: None | uavcan.si.unit.length.WideVector3_1_0 = None) -> None:
        """
        zubax.physics.kinematics.cartesian.Point.0.1
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param value: uavcan.si.unit.length.WideVector3.1.0 value
        """
        self._value: uavcan.si.unit.length.WideVector3_1_0

        if value is None:
            self.value = uavcan.si.unit.length.WideVector3_1_0()
        elif isinstance(value, uavcan.si.unit.length.WideVector3_1_0):
            self.value = value
        else:
            raise ValueError(f'value: expected uavcan.si.unit.length.WideVector3_1_0 '
                             f'got {type(value).__name__}')

    @property
    def value(self) -> uavcan.si.unit.length.WideVector3_1_0:
        """
        uavcan.si.unit.length.WideVector3.1.0 value
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._value

    @value.setter
    def value(self, x: uavcan.si.unit.length.WideVector3_1_0) -> None:
        if isinstance(x, uavcan.si.unit.length.WideVector3_1_0):
            self._value = x
        else:
            raise ValueError(f'value: expected uavcan.si.unit.length.WideVector3_1_0 got {type(x).__name__}')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.value._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        assert 192 <= (_ser_.current_bit_length - _base_offset_) <= 192, \
            'Bad serialization of zubax.physics.kinematics.cartesian.Point.0.1'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> Point_0_1:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "value"
        _des_.pad_to_alignment(8)
        _f0_ = uavcan.si.unit.length.WideVector3_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        self = Point_0_1(
            value=_f0_)
        _des_.pad_to_alignment(8)
        assert 192 <= (_des_.consumed_bit_length - _base_offset_) <= 192, \
            'Bad deserialization of zubax.physics.kinematics.cartesian.Point.0.1'
        assert isinstance(self, Point_0_1)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'value=%s' % self.value,
        ])
        return f'zubax.physics.kinematics.cartesian.Point.0.1({_o_0_})'

    _EXTENT_BYTES_ = 24

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.StructureType = _restore_constant_(
        'ABzY8LD0i!0{`t-+iw*`7(cz7-U}@)7Xjsf2nVzah-l@GBn`>f(ttr;$Y##&&>6aCce6WN&mkd^2Mw4>oP;sqPvC`ki5k3NeZx0j'
        'Oi26(_!D^3@7tZFrPvsse2{J0-#0toe7D*8ebW!SKifE5$se^XZu_YpIBv=kK?8A>HUj3jUet`ER7hsj@OhbJp3D;VUOQ&ymf3UN'
        'Tr+i5bwk>O`TEtYL0eAD+o|wUXI_M?NhOLNO(aVN4V~FYgwm)!cY!6Th(g0Fs`rAGZy8b{9Uq(PMh&`D%0x6WSZ6Mo)uMZ%WK?xZ'
        'u)tr6YQXiWq^`tJd1vvGSJn26E_e_~Dx547(g|2NC%N;!@Yx0C$tXE!crWiK9i)PR@S#hFkJ!~?YRf8NBnfRBH9jR;%zrnxcnV)V'
        'U8iA}1+2+JSp>COPH`fdLW%{@=${HADxbD8=r)9Oi?9tj33+-nm2NZgA<rFZ!)&=6mpP|lZW^bswjY^u5Tu(*8u~Qxmm9hPcA9h!'
        'Dw6r=_;Nx$344;lUQJmUY<zOP@?SlV|IDBK13721hU$mJW9kXnHl#~+yNv*X-Bs3fDK{vuTsbys=p7-8ojMOgTV2)VMzK+~)r_R='
        'W+MuOXVlm<YeukRSeLUgODKFfOMBGgdR)NA$d9UZ=UB|7_<OxhcOGKrr$BG*Ocn$*X|GfQTMIPEnEBMy$w{3yAoFgwDMCXQQJ^gp'
        'dU5}=fTC5>fvOcvIxTit?6z1%?9`;kj(ZWiH0iVBemfqpdV`2nO@{3JFyeqFYb>rs9MWXO&W~FCb@u(3wKHzV>#h9_h$EV8MC{XK'
        'lU@G;;;1H@t^F-le=Fi9O<qJ?r^!p!-ZsP@O=@=icEl~3>_FV0$;;N>POJY4Vy`B<Y+Sn$cWP2ctZA|bajPbKt-n_h$2ED)#yer{'
        'I5zHmh~1j(xBd?xPH6Hv;$BS-BJS4Y4eRF+;&x5mM0`n;w`{zV*5BKR>oqxS^E`sMR+FRF?=i%FO^(~VPuTjLwEoW^?$_j^jh7={'
        ')TD)YMw1(elbYN{tZQ<|`n_lKd4Ra6$wP~eEIux9y060un@XWx3X`R9rW7ug0xyMDDcmT9+of=)6z-M6gHm`{3Xe+Ru@y3)F4l@^'
        'nD-F-u7L*y=)T%yk|hRCiXXwTtpIUQHMXp|xQ%wvzOEVmIp3TDzxpgrm`5e^%}uq&y^N&p#!(_&;hPyX>ZVbacnl^2=EfA*Q}rSQ'
        'q5;e~3*E9ci*Iki3GdhkzIlZ0u_wvGFpuSfD492E1juWi&M|)i$z~#M8-8C6q*)_B%Fy<p+hh%38#iHdaJC_yrIrS>Jw+!osxuW}'
        '6uTL`w0y3{mvuDffV1C0Cq`li7;`yIA@BrS5%it~;W2ZQf5E?0BY7=~rXRvI_TKtGcp6;ZJDJ*;m&BEkn?#Y!?WK?@G^g+C{CoZb'
        '|B?U1@59f}e3Acx0r5k8GUqyegdex9HmAf{>iZ&`dxke*_5@rZ;$qs6KG^DMvdCxP_v~{9e9nOXHwNT)SJGZ_XTUQJgvY<SX09CW'
        's8sl9%D=wJznS6RK64t?Kz@C9bDmJue1ODO+~$oMSh~*x%RRZ#8?`3C(*wgCSmGG|0Qf}hJzZ+myeLZGumXvtwdit<)?!>#6JaeU'
        '2gmSVk!k*g+iLNz1mnLwlggE&kn5FW@Mm>;dH6*7o&T|tLHOO7qLj{G!zO19A`Jil'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
