# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2025-09-12 07:48:17.223183 UTC
# Namespace:     zubax.bridge

# There are no data types in this namespace. There may be data types in nested namespaces.
