# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2025-09-11 16:20:08.404227 UTC
# Namespace:     uavcan.internet

# There are no data types in this namespace. There may be data types in nested namespaces.
