# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/runner/work/packaged-dsdl-py/packaged-dsdl-py/submodules/zubax_dsdl/zubax/telega/DQ.1.0.dsdl
#
# Generated at:  2025-09-11 15:53:03.883581 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     zubax.telega.DQ
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class DQ_1_0:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 current: None | _NDArray_[_np_.float16] | list[float] = None,
                 voltage: None | _NDArray_[_np_.float16] | list[float] = None) -> None:
        """
        zubax.telega.DQ.1.0
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param current: truncated float16[2] current
        :param voltage: truncated float16[2] voltage
        """
        self._current: _NDArray_[_np_.float16]
        self._voltage: _NDArray_[_np_.float16]

        if current is None:
            self.current = _np_.zeros(2, _np_.float16)
        else:
            if isinstance(current, _np_.ndarray) and current.dtype == _np_.float16 and current.ndim == 1 and current.size == 2:  # type: ignore
                # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                self._current = current
            else:
                # Last resort, slow construction of a new array. New memory may be allocated.
                current = _np_.array(current, _np_.float16).flatten()
                if not current.size == 2:  # Length cannot be checked before casting and flattening
                    raise ValueError(f'current: invalid array length: not {current.size} == 2')
                self._current = current
            assert isinstance(self._current, _np_.ndarray)
            assert self._current.dtype == _np_.float16  # type: ignore
            assert self._current.ndim == 1
            assert len(self._current) == 2

        if voltage is None:
            self.voltage = _np_.zeros(2, _np_.float16)
        else:
            if isinstance(voltage, _np_.ndarray) and voltage.dtype == _np_.float16 and voltage.ndim == 1 and voltage.size == 2:  # type: ignore
                # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                self._voltage = voltage
            else:
                # Last resort, slow construction of a new array. New memory may be allocated.
                voltage = _np_.array(voltage, _np_.float16).flatten()
                if not voltage.size == 2:  # Length cannot be checked before casting and flattening
                    raise ValueError(f'voltage: invalid array length: not {voltage.size} == 2')
                self._voltage = voltage
            assert isinstance(self._voltage, _np_.ndarray)
            assert self._voltage.dtype == _np_.float16  # type: ignore
            assert self._voltage.ndim == 1
            assert len(self._voltage) == 2

    @property
    def current(self) -> _NDArray_[_np_.float16]:
        """
        truncated float16[2] current
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._current

    @current.setter
    def current(self, x: _NDArray_[_np_.float16] | list[float]) -> None:
        if isinstance(x, _np_.ndarray) and x.dtype == _np_.float16 and x.ndim == 1 and x.size == 2:  # type: ignore
            # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
            self._current = x
        else:
            # Last resort, slow construction of a new array. New memory may be allocated.
            x = _np_.array(x, _np_.float16).flatten()
            if not x.size == 2:  # Length cannot be checked before casting and flattening
                raise ValueError(f'current: invalid array length: not {x.size} == 2')
            self._current = x
        assert isinstance(self._current, _np_.ndarray)
        assert self._current.dtype == _np_.float16  # type: ignore
        assert self._current.ndim == 1
        assert len(self._current) == 2

    @property
    def voltage(self) -> _NDArray_[_np_.float16]:
        """
        truncated float16[2] voltage
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._voltage

    @voltage.setter
    def voltage(self, x: _NDArray_[_np_.float16] | list[float]) -> None:
        if isinstance(x, _np_.ndarray) and x.dtype == _np_.float16 and x.ndim == 1 and x.size == 2:  # type: ignore
            # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
            self._voltage = x
        else:
            # Last resort, slow construction of a new array. New memory may be allocated.
            x = _np_.array(x, _np_.float16).flatten()
            if not x.size == 2:  # Length cannot be checked before casting and flattening
                raise ValueError(f'voltage: invalid array length: not {x.size} == 2')
            self._voltage = x
        assert isinstance(self._voltage, _np_.ndarray)
        assert self._voltage.dtype == _np_.float16  # type: ignore
        assert self._voltage.ndim == 1
        assert len(self._voltage) == 2

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        assert len(self.current) == 2, 'self.current: truncated float16[2]'
        _ser_.add_aligned_array_of_standard_bit_length_primitives(self.current)
        assert len(self.voltage) == 2, 'self.voltage: truncated float16[2]'
        _ser_.add_aligned_array_of_standard_bit_length_primitives(self.voltage)
        _ser_.pad_to_alignment(8)
        assert 64 <= (_ser_.current_bit_length - _base_offset_) <= 64, \
            'Bad serialization of zubax.telega.DQ.1.0'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> DQ_1_0:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "current"
        _f0_ = _des_.fetch_aligned_array_of_standard_bit_length_primitives(_np_.float16, 2)
        assert len(_f0_) == 2, 'truncated float16[2]'
        # Temporary _f1_ holds the value of "voltage"
        _f1_ = _des_.fetch_aligned_array_of_standard_bit_length_primitives(_np_.float16, 2)
        assert len(_f1_) == 2, 'truncated float16[2]'
        self = DQ_1_0(
            current=_f0_,
            voltage=_f1_)
        _des_.pad_to_alignment(8)
        assert 64 <= (_des_.consumed_bit_length - _base_offset_) <= 64, \
            'Bad deserialization of zubax.telega.DQ.1.0'
        assert isinstance(self, DQ_1_0)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'current=%s' % _np_.array2string(self.current, separator=',', edgeitems=10, threshold=100, max_line_width=1000000),
            'voltage=%s' % _np_.array2string(self.voltage, separator=',', edgeitems=10, threshold=100, max_line_width=1000000),
        ])
        return f'zubax.telega.DQ.1.0({_o_0_})'

    _EXTENT_BYTES_ = 8

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.StructureType = _restore_constant_(
        'ABzY8U+}_c0{?YX-%k`V5IztDQREcG_#=S_HJHe%(P)T?LBaE30TGOe52oqv)|*OqyLQ|2&cs9>Fq$-xg!=#aPx!3U-Ge&>?sB>5'
        '%=DXYrZe+(=+~d&TKTclc_%3n5s-o@P6hu=Bf$a^%QTk-*UZ`R4XsS9jbg7mIdi-2)|UI?X6-P^Xo~iU&nBYnKr_LbG+27&>?mn5'
        'RdAU(sM(P>U3u4q17Yo(+j90ap;{{*8O;j!4zZ45vG3*VaDy|E^rDZEglbB(r(~}lb6qLgarQ!kw^_2xvZjWoUUe{!ae~ZKmgz3o'
        'F<f%RQ?7XnJx(=*r1~JrX%cZwL>a_|b>tV*LX%V`%)u2qwYGQNUket|w&G2`DBErwNs>a-ETJmt2l|dUDQ#w4o5TlxuV}2Xm<1NO'
        '(UlQn<@euk;2Xl2$ezN$IgPpQxNy)8kw~EP&Aps@*qEOF|Lp9UXIxj6+Q4HsJ9~o2+}WAqK#EQpNx@@hCs$Z1v0|Rr%bY2yrRvq_'
        'B#D9JBf<lFex2n^^P~L+$tH4#dGwoDH9}C;`QHh#T2vV3e!AJPzEeb)`4CBY=E4~-(6$#weEp4}9yJ{BuC<+TwE8z#TGq~KRyOCV'
        'i97}j+mYBPh27u~CXtv^4XX<EiW*G9R9CtT*SgYlSce(74mZBTO}N$f7H}K0n1j2eAKZtB-3#;ZxGOy=(_E+=7JIqC^Kb?l_<Qli'
        '?GY~^>|@!ILenPp)(W7O*~z|<B2lNBO&?+z&Orn(4R&b4a>Zh*S>k@!v*f)W3zAEv2~XUrJx2;@RLsyI7|AL2pB?dkf=AeUYq$^E'
        'YhJsHZ!~ZR3k1?HfRoB(8B=)vB-N&~b!@*)<d)3&cA3jN4x}9`OjJGwPP`o}R|fHBob2*|Fx3XZ?XdJJxEI_FO0)LEF-d?H$jHBo'
        'AIlbxnfu{WxAij9YF}k&uJ*|x%t72s%w8(9B3cq9r7mw4NEWO3VHP$)KnfX1{O0fxln;IM^I>1E(Inwn^HB4mwcqdJqRf27vm-~s'
        '538RD%*)g6yScqDJ;HUGSHZ9q4z@<w5%883Ub}$Wg`U=hqvo*Mw@>g7M{S4r00sa6'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
