# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/runner/work/packaged-dsdl-py/packaged-dsdl-py/submodules/zubax_dsdl/zubax/telega/ServoCommand.1.0.dsdl
#
# Generated at:  2025-09-11 16:20:11.547802 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     zubax.telega.ServoCommand
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import zubax.physics.dynamics

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class ServoCommand_1_0:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 target:                            None | zubax.physics.dynamics.DoF2nd_1_0 = None,
                 profile_velocity_reverse_forward:  None | _NDArray_[_np_.float32] | list[float] = None,
                 profile_deceleration_acceleration: None | _NDArray_[_np_.float32] | list[float] = None,
                 profile_jerk:                      None | int | float | _np_.float32 = None) -> None:
        """
        zubax.telega.ServoCommand.1.0
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param target:                            zubax.physics.dynamics.DoF2nd.1.0 target
        :param profile_velocity_reverse_forward:  saturated float32[2] profile_velocity_reverse_forward
        :param profile_deceleration_acceleration: saturated float32[2] profile_deceleration_acceleration
        :param profile_jerk:                      saturated float32 profile_jerk
        """
        self._target:                            zubax.physics.dynamics.DoF2nd_1_0
        self._profile_velocity_reverse_forward:  _NDArray_[_np_.float32]
        self._profile_deceleration_acceleration: _NDArray_[_np_.float32]
        self._profile_jerk:                      float

        if target is None:
            self.target = zubax.physics.dynamics.DoF2nd_1_0()
        elif isinstance(target, zubax.physics.dynamics.DoF2nd_1_0):
            self.target = target
        else:
            raise ValueError(f'target: expected zubax.physics.dynamics.DoF2nd_1_0 '
                             f'got {type(target).__name__}')

        if profile_velocity_reverse_forward is None:
            self.profile_velocity_reverse_forward = _np_.zeros(2, _np_.float32)
        else:
            if isinstance(profile_velocity_reverse_forward, _np_.ndarray) and profile_velocity_reverse_forward.dtype == _np_.float32 and profile_velocity_reverse_forward.ndim == 1 and profile_velocity_reverse_forward.size == 2:  # type: ignore
                # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                self._profile_velocity_reverse_forward = profile_velocity_reverse_forward
            else:
                # Last resort, slow construction of a new array. New memory may be allocated.
                profile_velocity_reverse_forward = _np_.array(profile_velocity_reverse_forward, _np_.float32).flatten()
                if not profile_velocity_reverse_forward.size == 2:  # Length cannot be checked before casting and flattening
                    raise ValueError(f'profile_velocity_reverse_forward: invalid array length: not {profile_velocity_reverse_forward.size} == 2')
                self._profile_velocity_reverse_forward = profile_velocity_reverse_forward
            assert isinstance(self._profile_velocity_reverse_forward, _np_.ndarray)
            assert self._profile_velocity_reverse_forward.dtype == _np_.float32  # type: ignore
            assert self._profile_velocity_reverse_forward.ndim == 1
            assert len(self._profile_velocity_reverse_forward) == 2

        if profile_deceleration_acceleration is None:
            self.profile_deceleration_acceleration = _np_.zeros(2, _np_.float32)
        else:
            if isinstance(profile_deceleration_acceleration, _np_.ndarray) and profile_deceleration_acceleration.dtype == _np_.float32 and profile_deceleration_acceleration.ndim == 1 and profile_deceleration_acceleration.size == 2:  # type: ignore
                # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                self._profile_deceleration_acceleration = profile_deceleration_acceleration
            else:
                # Last resort, slow construction of a new array. New memory may be allocated.
                profile_deceleration_acceleration = _np_.array(profile_deceleration_acceleration, _np_.float32).flatten()
                if not profile_deceleration_acceleration.size == 2:  # Length cannot be checked before casting and flattening
                    raise ValueError(f'profile_deceleration_acceleration: invalid array length: not {profile_deceleration_acceleration.size} == 2')
                self._profile_deceleration_acceleration = profile_deceleration_acceleration
            assert isinstance(self._profile_deceleration_acceleration, _np_.ndarray)
            assert self._profile_deceleration_acceleration.dtype == _np_.float32  # type: ignore
            assert self._profile_deceleration_acceleration.ndim == 1
            assert len(self._profile_deceleration_acceleration) == 2

        self.profile_jerk = profile_jerk if profile_jerk is not None else 0.0  # type: ignore

    @property
    def target(self) -> zubax.physics.dynamics.DoF2nd_1_0:
        """
        zubax.physics.dynamics.DoF2nd.1.0 target
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._target

    @target.setter
    def target(self, x: zubax.physics.dynamics.DoF2nd_1_0) -> None:
        if isinstance(x, zubax.physics.dynamics.DoF2nd_1_0):
            self._target = x
        else:
            raise ValueError(f'target: expected zubax.physics.dynamics.DoF2nd_1_0 got {type(x).__name__}')

    @property
    def profile_velocity_reverse_forward(self) -> _NDArray_[_np_.float32]:
        """
        saturated float32[2] profile_velocity_reverse_forward
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._profile_velocity_reverse_forward

    @profile_velocity_reverse_forward.setter
    def profile_velocity_reverse_forward(self, x: _NDArray_[_np_.float32] | list[float]) -> None:
        if isinstance(x, _np_.ndarray) and x.dtype == _np_.float32 and x.ndim == 1 and x.size == 2:  # type: ignore
            # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
            self._profile_velocity_reverse_forward = x
        else:
            # Last resort, slow construction of a new array. New memory may be allocated.
            x = _np_.array(x, _np_.float32).flatten()
            if not x.size == 2:  # Length cannot be checked before casting and flattening
                raise ValueError(f'profile_velocity_reverse_forward: invalid array length: not {x.size} == 2')
            self._profile_velocity_reverse_forward = x
        assert isinstance(self._profile_velocity_reverse_forward, _np_.ndarray)
        assert self._profile_velocity_reverse_forward.dtype == _np_.float32  # type: ignore
        assert self._profile_velocity_reverse_forward.ndim == 1
        assert len(self._profile_velocity_reverse_forward) == 2

    @property
    def profile_deceleration_acceleration(self) -> _NDArray_[_np_.float32]:
        """
        saturated float32[2] profile_deceleration_acceleration
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._profile_deceleration_acceleration

    @profile_deceleration_acceleration.setter
    def profile_deceleration_acceleration(self, x: _NDArray_[_np_.float32] | list[float]) -> None:
        if isinstance(x, _np_.ndarray) and x.dtype == _np_.float32 and x.ndim == 1 and x.size == 2:  # type: ignore
            # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
            self._profile_deceleration_acceleration = x
        else:
            # Last resort, slow construction of a new array. New memory may be allocated.
            x = _np_.array(x, _np_.float32).flatten()
            if not x.size == 2:  # Length cannot be checked before casting and flattening
                raise ValueError(f'profile_deceleration_acceleration: invalid array length: not {x.size} == 2')
            self._profile_deceleration_acceleration = x
        assert isinstance(self._profile_deceleration_acceleration, _np_.ndarray)
        assert self._profile_deceleration_acceleration.dtype == _np_.float32  # type: ignore
        assert self._profile_deceleration_acceleration.ndim == 1
        assert len(self._profile_deceleration_acceleration) == 2

    @property
    def profile_jerk(self) -> float:
        """
        saturated float32 profile_jerk
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._profile_jerk

    @profile_jerk.setter
    def profile_jerk(self, x: int | float | _np_.float32) -> None:
        """Raises ValueError if the value is finite and outside of the permitted range, regardless of the cast mode."""
        x = float(x)
        in_range = -340282346638528859811704183484516925440.0 <= x <= 340282346638528859811704183484516925440.0
        if in_range or not _np_.isfinite(x):
            self._profile_jerk = x
        else:
            raise ValueError(f'profile_jerk: value {x} is not in [-340282346638528859811704183484516925440, 340282346638528859811704183484516925440]')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.target._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        assert len(self.profile_velocity_reverse_forward) == 2, 'self.profile_velocity_reverse_forward: saturated float32[2]'
        _ser_.add_aligned_array_of_standard_bit_length_primitives(self.profile_velocity_reverse_forward)
        assert len(self.profile_deceleration_acceleration) == 2, 'self.profile_deceleration_acceleration: saturated float32[2]'
        _ser_.add_aligned_array_of_standard_bit_length_primitives(self.profile_deceleration_acceleration)
        if _np_.isfinite(self.profile_jerk):
            if self.profile_jerk > 340282346638528859811704183484516925440.0:
                _ser_.add_aligned_f32(340282346638528859811704183484516925440.0)
            elif self.profile_jerk < -340282346638528859811704183484516925440.0:
                _ser_.add_aligned_f32(-340282346638528859811704183484516925440.0)
            else:
                _ser_.add_aligned_f32(self.profile_jerk)
        else:
            _ser_.add_aligned_f32(self.profile_jerk)
        _ser_.pad_to_alignment(8)
        assert 256 <= (_ser_.current_bit_length - _base_offset_) <= 256, \
            'Bad serialization of zubax.telega.ServoCommand.1.0'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> ServoCommand_1_0:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "target"
        _des_.pad_to_alignment(8)
        _f0_ = zubax.physics.dynamics.DoF2nd_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f1_ holds the value of "profile_velocity_reverse_forward"
        _f1_ = _des_.fetch_aligned_array_of_standard_bit_length_primitives(_np_.float32, 2)
        assert len(_f1_) == 2, 'saturated float32[2]'
        # Temporary _f2_ holds the value of "profile_deceleration_acceleration"
        _f2_ = _des_.fetch_aligned_array_of_standard_bit_length_primitives(_np_.float32, 2)
        assert len(_f2_) == 2, 'saturated float32[2]'
        # Temporary _f3_ holds the value of "profile_jerk"
        _f3_ = _des_.fetch_aligned_f32()
        self = ServoCommand_1_0(
            target=_f0_,
            profile_velocity_reverse_forward=_f1_,
            profile_deceleration_acceleration=_f2_,
            profile_jerk=_f3_)
        _des_.pad_to_alignment(8)
        assert 256 <= (_des_.consumed_bit_length - _base_offset_) <= 256, \
            'Bad deserialization of zubax.telega.ServoCommand.1.0'
        assert isinstance(self, ServoCommand_1_0)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'target=%s' % self.target,
            'profile_velocity_reverse_forward=%s' % _np_.array2string(self.profile_velocity_reverse_forward, separator=',', edgeitems=10, threshold=100, max_line_width=1000000),
            'profile_deceleration_acceleration=%s' % _np_.array2string(self.profile_deceleration_acceleration, separator=',', edgeitems=10, threshold=100, max_line_width=1000000),
            'profile_jerk=%s' % self.profile_jerk,
        ])
        return f'zubax.telega.ServoCommand.1.0({_o_0_})'

    _EXTENT_BYTES_ = 63

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.DelimitedType = _restore_constant_(
        'ABzY8yY|9p0{^{OTW=gm6`sk(@lKr029xXpLMdLrX6+8kMFKY5l3=hVcDzY;S?v<_R(F@@l-<+Ssj41(0xPjXL`f*YN@?H;Y5xGf'
        '0`Y*v3lb6%PmA`MXLg^$sjBXo9((LS0@$*rx-O^A<vZUwJwG}2tKodh{h0IlFi}Ywgo;T{Q+|g=DGS0_^mC!OW~DiGg{8cY!{p{L'
        'XXV3k@tyMRa>2}mJj<9Yp=D0p(6WeiA=%`X<6%boDB=@$iiqw8nx(8qgBwf^#AVU%(<~{?Y&c+2agkX;Ctj<@56f=5+qzr6Q<{?@'
        ')mrkX&`g!LQ0f6Hk9L*j_zGufGS;ILCREc<Tjk({pM;M2v{x&Kq2jR$k|Anq2Uo<(7g05sgJ)|k;0)djXRD(xG=!X=6tc}T)~EX4'
        '6LXL$xwH=F12pBCl~hnY>DH5B#C4dmtf!&u5;QNSN{4-spm~et+(v!e9t$qx+L~QLpSFHhUN6nZL#5I8R3=S9_fSrs_A;)E#9q89'
        'X{<383S+cVjZwyfGp**&qeqWg-S%A+TSVxMS%(_C(;N#E5tpWA7sifzu^I(k0vF&*@a22(75M67gbr9LVy=fJT!e2F5i|1*OoY+U'
        '!_10(89oPB;F|^dC}Fu|F-6>#_sz56Cf{XAm<y>xo|Nn6OsGU5V}=VU3v-GdFemIs$|JOX1MS$|u(J=*<LwJ*4+x9p8Cf{kn`1jd'
        'ZkOh{oW|R<$C70m$>kiCe8qHB5n(ur6d`Lm4k4jkMrgVRdzA+aE{`Eon$sRM!Arpx0(U^$fX#<M73wHirY%$kJZ9y6xM(h|i2>{5'
        'ETO5$dW2?#?s7%m>@&^eEg~e5LQ@+MLL*V=@eWB7PP1D9THxI0Q$9mkKFc1X=uCxfW}bJ>3$+NP5ZcL7=o5tE)dg6Cb+`r_@CyE3'
        'hZ}Iy*>fz6Qk3!88vSDwqIG)jb7|%-aedW2-@wNz56sa}<fS182~op-BvOtLoL^&ofw^Vfa4lz&Y9X6E76V7NfYhAcph?2B-o8z6'
        '8?w<THD@o2%pxnBD$+dTC1SL!CmSbKL&oX#B2B3r?mImb4rp4i@|Wd8m%OVYWXRmBg`8MK=)6A9Y}(@h1B8PUp~D)*)7@Ento5$K'
        'WM;cL%^aJqV;cR`Nr$_&Sf(Pl-~Bc`z`vh24#F?&?t9(Y;*fO}xx{QD!l&j_X8Q3>AuVz)noqu&u^lZkhv91cd5>z`%HX?J^snJO'
        '{1$#w!1wOM_t#-{D&pW(Gh0)82|us^gg0#Rym5H)EHyQFOcpIoY8aI8!|6FR)?}PP5FMB)zyN&Qwx_~qJU8^)etZz%1ctPISV#{5'
        '$XmGktwR8Ez<LFc8BJvmQx-11{$jh;THPcX81a*&W_5y&%tW?)he@$SC_z`&TNH>QO^9T9ij0DXaVv5Z*#VXjuI)+5XbdbNS`a!A'
        'JRw5G95c(6uAp-h?{lEKfH`)%V8kUCL55IX7eDJdoPexgs721Q<y45ASf&-qhF@uxW1cE|=jbRFQ9MoJLRwz-S7}s7J4}g9YYLj>'
        'E8<{}8ty`?Kkw(ML!r}nIboZaQ%NvUHO;3EXnCZhL#*d3wzheK{EnTPY!^<2%->KoK>u-KT0)~p>9zuQk4(p8YCd+I<xKPGBzq*>'
        'wnuO8L)j!G7rJeaq8d#_6HO$S!d2@UIiX~>dBhqn<PNqomN>rlqYRr&>+mH~yZ-H$ZPZ94G+3NipxIA_eu*_fm(wEElP-rpR-->X'
        '0g?UrATRy38vX65ees#v7YU2e4C&Al(s=yv-*m>4aQR%V;TFR_36)u>HSh`?dUr+ezlU@1clZPR6Fz`P@X_H!k8I;!FiLZ_`HC^w'
        'OF8O){ld{!%k60-H;F~2rAP_(FA5vFptI@{G+~POFePpNl0qT*aP*u_vE|j*FyZMI>MrDv*c`#M^t4e4!(db-RA6JR2)1yT`Wd5='
        'EVx>+M118~Y*rbXk_BH`>SbS87Eu{wC)*1k4LTCS3Y=K3ahC=icU5Ho@m!*soLjf&SizDp0sH#r?6Q0N!fmPIXZ@nkOpcx5*E@E7'
        'bk32OLS20tI-yl6E-pDyO+b#eHzDiJG<Pj7b?lTQ*kK>dmOLgFLKR1Qn%zU9sNyE?;rnMoIEo|+7qGb^n^XbH3_4f+)f%XFF=ztN'
        'K2xQNzON#Yja5a%OIF+t@E9<<%2Pg%X_^j+eYqIlT0z$b7(tR?D6T~|D9m5#N>?2i94hRavRamHy-~0Qj|;+9p|rIESJ8-3%v|XT'
        'I+uoIz@<j}g|DZ!gm4UqH;3(FV`|$zBJuqL3u>C~ji?i(@Ge|JbF1>2_{*mowzs7j<=WiD>-_(xnfYJr{N1QQ8nraO)A@^Ugx<s1'
        '_r|mJ<~`H@@SESq+4uKv-ZMS5<63LA;eq|vIPF@keG9%4z)6^c=lmB7=a4EtfRCPpJhzTuf3|fL|BYC3YX+a5I_mg#;t;9JwGZ3o'
        '9M&uUZITRu(F8wyQ?h90U(Gzxu4bC`n4D;0s><_Hw{5?{!1{xxPlZ!6%zOPi(XKpyon}3DSkE#OZu>W^Z|$kovvsX*VL(1?@9%y+'
        '2nepeaAbOK9Q+GA(JMNH6951'
    )
    assert isinstance(_MODEL_, _pydsdl_.DelimitedType)
