# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2025-11-24 13:46:53.944917 UTC
# Namespace:     uavcan.si.unit.voltage

from uavcan.si.unit.voltage.Scalar_1_0 import Scalar_1_0 as Scalar_1_0

# Convenience aliases of the newest minor versions known at the time of code generation.
Scalar_1 = Scalar_1_0
