# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2025-10-27 13:51:00.269151 UTC
# Namespace:     uavcan.si.unit.angle

from uavcan.si.unit.angle.NarrowScalar_1_0 import NarrowScalar_1_0 as NarrowScalar_1_0
from uavcan.si.unit.angle.NarrowVector3_1_0 import NarrowVector3_1_0 as NarrowVector3_1_0
from uavcan.si.unit.angle.Quaternion_1_0 import Quaternion_1_0 as Quaternion_1_0
from uavcan.si.unit.angle.Scalar_1_0 import Scalar_1_0 as Scalar_1_0
from uavcan.si.unit.angle.Vector3_1_0 import Vector3_1_0 as Vector3_1_0
from uavcan.si.unit.angle.WideScalar_1_0 import WideScalar_1_0 as WideScalar_1_0
from uavcan.si.unit.angle.WideVector3_1_0 import WideVector3_1_0 as WideVector3_1_0

# Convenience aliases of the newest minor versions known at the time of code generation.
NarrowScalar_1 = NarrowScalar_1_0
NarrowVector3_1 = NarrowVector3_1_0
Quaternion_1 = Quaternion_1_0
Scalar_1 = Scalar_1_0
Vector3_1 = Vector3_1_0
WideScalar_1 = WideScalar_1_0
WideVector3_1 = WideVector3_1_0
